---
title: "Conservation Biology (BI328)"
description: | 
  Fall 2020 - Assignments
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

```

# Class & Lab Participation

Next to traditional in-class lab & lecture participation we have two assignments to help you engage with the covered material inside and outside the classroom.

### LECTURE DEBRIEF

This assignment is meant to be a quick reflection on the material covered during class to help me assess where everyone is at and to help you follow up. After each lecture, you will answer these four questions (very, very) briefly.

*	What was the most muddy concept(s)? Do we need to further clarify?
*	What was the exciting, interesting, or a new concept you learned?
*	Was there any “assumed background knowledge” you did not have? Do we need to further clarify?
*	Any additional general comments or questions on today's lecture or this week’s lab?

Submit your answers [`r icon::fa("clipboard-list")`](https://docs.google.com/forms/d/e/1FAIpQLSf_wpIenOLXtsZ24-3Aa120mgZmN3ioZHVkA342ZCYOj5OQug/viewform?usp=sf_link).

**Due by 3pm the day after lecture.**  
No late work will be accepted or receive credit.

**Some additional remarks**

1. The Lecture Debriefs are for *me* - they help me gauge where everybody is at, if I'm making assumptions about background knowledge that aren't correct, and that everybody is following during lecture - the eyes may be the window to the soul but it is not easy to read the room when I can't see everyone face. When you are filling out the form make sure that I can follow what you are saying - it does not have to be eloquent prose (or even complete sentences) but I do need to be able to understand what you are saying, so please be precise.
2. The Lecture Debriefs are for *you* - they should put you in the habit of pausing for a few minutes after lecture and make sure you are keeping up. When I see that multiple people are unclear about the same thing or that I need to back-up and give you some additional background knowledge I will do my best provide that but if I don't directly answer your question during a lecture and you are still unclear (sometimes the content of the next lecture or two will clarify questions) then you should come see me during office hours to answer your questions.
3. It is a high frequency/low stakes assignment (overall this accounts for 2.7% of your total grade, not that I'm discouraging you from taking this serious) and we are operating on the check mark scale which essentially is pass fail but you still need to meet the standard. This means you should **always answer the first two questions** - they are intentionally worded as "most ..." they should also always be answer in the format of "concept - why/what part?"; especially the answer "most muddy" concept should specify why it's unclear/what component is unclear, even if you figured it yourself during lecture (go you!) and don't need further clarification briefly summarizing what was unclear and how you figured it out and/or what you think the answer is helps you and me. Accurately diagnosing a problem is half the answer. You can also think of the "most muddy" concept as "this is the concept I'm still mulling over".
4. Make sure your answers match the question; occasionally some of your answers have classified one of the main topics of the course as "assumed background knowledge"; assumed background knowledge would be for example that I assumed everybody was up on their life history strategies.

This should take you at most 10-15 (focused) minutes to complete.


### CONSERVATION IRL
It is important to learn to make connections between the topics and concepts we cover during class and the real world. You will find that once you are aware of it that you encounter “Conservation Biology” all. the. time.  
For this weekly assignment you will share one of these encounters in 5-10 sentences with the class using our slack channel. This could be a podcast you listened to, an interesting documentary you watched, an article or essay in the news, a conversation you had with somebody in person or on social media, ...  
It does not have to be a “positive” encounter – this could also be a statement/article you came across that you think is incorrect or a position you disagree with. Whenever possible post a link for everyone who is interested to be able to follow up. Here are a few prompts to guide your post:

*	Give a concise 1 – 2 sentence summary or state the main point that stuck out to you.
*	How does it connect to our class?
*	What did you find helpful?
*	What new thing did you learn?
*	Is there a question that came up you would like to clarify?
*	Was there some information you found unsettling? Did something seem incorrect?
*	Was your encounter extremely biased in a certain direction?

**Due by Sunday 5pm each week** though you are encouraged to post at any time during the week.  
No late work will be accepted or receive credit.  
*If you post an initial ‘Conservation IRL’ by Aug 23rd (first half week of classes) you may cash that freebie in later that semester if needed.*


### READING REFLECTIONS

You should be reading assigned chapters and other materials before each lecture. Check our course site for the most upcoming readings to make sure you are not missing any. Readings will be assigned at least three days in advance. The reading reflections should be about 500 words (no less than 300 words), try not to go over 750 words (be concise). This assignment is supposed to help me gauge what you are getting out of the readings and to help you hold yourself accountable to actually engage with the material. A good way to approach this is to take notes while your read, then summarize those – this will help you pull out the most important information. Remember, our final is cumulative and open book, so good note-keeping will pay off down the line.

For book chapters, review articles, or reports a good starting point is to list the most important concepts and/or major conclusions, and if appropriate relevant case studies supporting those. For research articles draw out the central hypothesis being tested, or question asked, what type of data set was generated to answer the question, and key results/major conclusions. In all cases, you will want to list statements/keywords that were unclear, that you have questions about or disagree with, or flaws you see in the line of argument.

Each reading reflection should be submitted as a word document through `Canvas`. Double space and use a legible font (Times new Roman/Cambria, Arial/Calibri) and font size (11 - 12 pts). Name your file `BI328_lastname_reading_month-day.docx`. Create a header or footer with your Name, Page number, and course designation/semester, for each chapter/paper title that section in bold to indicate the source.  
I've provided a template of what that submission could look like [`r icon::fa("file-download")`](/files/BI328_OLeary_reading_08-28.docx).

**Due by Friday 5pm each week** (covering that week's readings).  
No late work will be accepted or receive credit. The first reading reflection is due Aug. 28th covering reading assigned for Aug 24th - 28th.

**Some additional remarks**

You should be summarizing the assigned chapters/other readings independent of the extent to which we covered them

This is what I would consider an outline:

> Three levels of hierarchical diversity  
- Ecosystem diversity  
- Species diversity  
- Genetic diversity  
Quantifying/Describing biodiversity  
- Compositional  
- Structural  
- Functional  

This would be "notes" that are more helpful to you as somebody who has read the chapter as opposed to somebody who hasn't read the chapter.
This would be more appropriate:

> Biodiversity [is] generally defined at three hierarchical levels, ecosystem, species, and genetic diversity.  
[There are] Three perspectives that shape how we try to describe and quantify biodiversity, compositional (which genes/species/ecosystems are present), structural (how are they distributed), and functional (what is their role).

So you could drop the parts in [], even though that's poor English and not a "complete sentence". A good point of orientation is whether somebody who didn't read the chapter would get the bird's eye view of what's going on. 
The focus on "complete thoughts" means that you don't necessarily have to link all the concepts, instead you can let them stand on their own. You can also think of it as if you were writing up all the topic sentences for a set of paragraphs. If you look at the end of each chapter in your book, they write up a set of summary statements - I'm looking for a similar format though I'm always slightly hesitant to point this out because then there is a temptation to just read the chapter summaries. It is helpful if you use paragraphs to break up your concepts within a chapter.

Why are we calling it "reflection" and not "summary"? Because you should add your own insights when appropriate - this will become more important as we shift from readings in our textbook to papers where you will want to point out flaws, points of disagreement or why this is impactful. This is partially why you are handing in reading reflections at the end of the week when we've also covered that material in class. So to stick with the example above, you could instead write that first sentence as such:

> Biodiversity generally defined at three hierarchical levels, ecosystem, species, and genetic diversity; these categories are helpful organize thinking/research but because they exist on a spectrum not always well defined (e.g. boundaries of an ecosystem).

This summarizes the central concept that biodiversity has different levels - but you've also thought about how you need to create categories because biodiversity is such a broad term but also it can be difficult to clearly delineate. As a rule of thumb if you are uncertain about this part, when in doubt, stick to the summary part]?

Another example would be the difference between

> Mass extinctions can have external (volcanic activity, meteor impacts, climate) and internal (microbes, viruses,...) causes. The big five extinctions are all attributed to external causes.

and

>Mass extinctions can have external (volcanic activity, meteor impacts, climate) and internal (microbes, viruses,...) causes.  The big five extinctions are all attributed to external causes - internal causes are unlikely to cause mass extinctions because by definition these affect biodiversity across a wide taxonomic range.


# Writing assignments & presentations

### ANNOTATED BIBLIOGRAPHY 
Over the course of the semester, you will maintain an annotated bibliography as a “living document”.  
This will include your readings for lectures, labs, articles you shared for the “conservation IRL” assignment, and resources for your conservation biology case studies and term paper.  
[Details](https://bi328.netlify.app/bibliography.html).


### CONSERVATION BIOLOGY CASE STUDY
Over the course of the semester you will dig into three case studies in several formats.  
Topics may include for example, conservation efforts for an endangered species or ecosystem, biography of a conservation biologist or environmental scientist, or a specific piece of legislation.  
[Details](https://bi328.netlify.app/case-study.html).


### TERM PAPER
If I gave you $1 billion to invest in conservation – how would you spend it and why?  
This assignment is structure to give you all semester to come develop an answer.  
[Details](https://bi328.netlify.app/termpaper.html).