---
title: "Conservation Biology (BI328)"
description: |
  Fall 2020 Course Site
site: distill::distill_website

---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

```

# Course Details

Download a hard copy of the syllabus [`r icon::fa("file-download")`](/files/BI328_Syllabus_F2020.pdf).

::: l-body
|.                 |.                                                |
|-----------------|------------------------------------------------|
| **Instructor:**   | [Shannon J. O'Leary](https://olab.netlify.app/)|
|                   | office: GOUL 2321                              |
|                   | `r icon::fa("envelope")` shannon.j.oleary[at]gmail[dot]com |
| **Office Hours:** | `r icon::fa("home")` Monday, Tuesday, Friday 11:30am - 1pm (or by appointment)  |
| **Lectures:** | `r icon::fa("chalkboard-teacher")` Monday/Wednesday/Friday 10:20 - 11:10am (GOUL3102) |
| **Lab:** | `r icon::fa("flask")` Wednesday 1:30 - 4:30pm (GOUL3102) |
:::

# Course Objectives

After completing this course, you should be able to

1.	Describe what biodiversity is, how we measure levels of biodiversity, and the value thereof.
2.	Explain the patterns and processes leading to the observed ongoing, drastic decline in biodiversity. 
3.	Apply fundamental principles from a variety of fields, including ecology, genetics, systematics, toxicology, economics, and creative problem-solving to management and conservation of biodiversity.
4.  Apply the theoretical framework, field, lab, and computational techniques to current management and conservation concerns, including
    + Being able to evaluate sources/content of information.
    + Gaining an overview of commonly used techniques to monitor biodiversity.
    + Understanding how large data sets & modeling can be used to enable sound conservation/management decision-making.
    
    
# Your road to success

**Come prepared:** 
Read relevant textbook chapters and assigned readings before class; be familiar with content, have an idea of hazy/difficult concepts and identify knowledge gaps.
(*Accountability mechanism: Reading reflections*)

**Be present & focused:**
Engage with the material, take notes, ask questions, participate in discussions. Participating might mean speaking up more than you are usually comfortable with so challenge yourself to go outside your comfort zone – which for some of us might mean listening more.
(*Accountability mechanism: Class/lab participation*)

**Debrief:**
Figure out what wasn’t clear and follow up as quickly as possible at beginning of next class, via slack/office hours, or talk to your classmates. 
(*Accountability mechanism: Lecture Debrief*)

**Review:**
Work through the re-cap questions, find a study buddy/group, come to Q&A sessions, and make use of office hours. 
(*Accountability mechanisms: Re-cap questions, Exams*)

**Plan ahead & manage your time:**
I realize this is not your only class (it might not even be your “most important” class), so I will do my best to clearly communicate deadlines and expectations to help you with your time management. Keep track of due dates, block of regular time blocks for reading/review/lab homework and anticipate deadlines. If this is something you struggle with, I am happy to help you explore some time management techniques that work for you.
(*Accountability mechanism: Weekly low-stakes assignments, assignments throughout semester*)
