---
title: "Conservation Biology (BI328)"
description: | 
  Fall 2020 Lectures
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

```

# Sustainable Development & Semester Wrap-up

### Assigned readings

**Reading reflections due: Nov. 20th, 5pm**

`r icon::fa("book-reader")` Schellenberg, ["On Behalf Of Environmentalists, I Apologize For The Climate Scare"](https://environmentalprogress.org/big-news/2020/6/29/on-behalf-of-environmentalists-i-apologize-for-the-climate-scare)

Format for this reading assignment: 500 words (min. 300/max 750); give brief summary of Schellenberg's main arguments/central points and then give your position on the article - do you agree/disagree (with some parts/all parts), how does this relate to what you have learned this semester etc.



<br>


### Outline

**Sustainable Development**

* Definition (World Commission on Environment & Development, 1987): “development that meets the needs of the present without compromising the ability of future generations to meet their own needs” 
* Three imperatives that sustainable development abides by
    + Environmental: Stay within carrying capacity of the planet (Protect biodiversity & ecosystem services)
    + Economic: Provide an adequate material standard of living for all (Create opportunities for growth & advancement)
    + Social: Provide systems of governance that propagate the values that people want to live by
 (Build high quality life for all)
* Intersects of these spheres carry imperatives
    + Environmental/Social: Protections of natural systems must be socially acceptable
    + Environmental/Economic: Growth must be ecologically viable
    + Economic/Social: Wealth should be distributed ethically & justly
* Sustainable development attempts to uphold all six of these imperatives
* Sustainable development goals
* Protecting, restoring and managing biodiversity fits within the goals of sustainable development

**Ecomodernism (environmental philosophy)**

* Worldview, values, and ethics influence decision-making in conservation
    + (idealized) differentiation of scientist offering value-neutral informatio/expertise vs advocate supporting/recommending certain causes & policies
    + Worldview, values, and ethics influence the questions we think are worth asking and how we interpret the answers we get
* Three major (but fuzzy) categories to determine the value of biodiversity for human well-being
    + intrinsic value
    + utilitarian value
    + relational value
* Environmental ethics (value systems) shape how we determine the value of biodiversity
    + Technocentrism: humans should aspire to dominate nature through technology to control all aspects of global environment to suit human needs/maximize human prosperity
    + Anthropocentricism: human beings are primary holders of moral standing in the world/nature seen primarily in terms of its value & benefit to humans & their experiences
    + Biocentrism: extends inherent value/more consideration to all living beings (not just humans)
    + Ecocentrism: more consideration to transorganismic entities (species, biotic communities, ecosystems, and biodiversity)/recognizes earth’s living/nonliving systems as a whole, rather than recognizing just the value of individual organisms (biocentricism)
* Philosophical differences result in disagreements in the perception of root causes of (biodiversity/climate) crisis and solutions to move the world to a better future
    + Malthusians: There is a limited capacity in terms of the resources available to support human population - once humans exceed that capacity we will hit a critical point.
    + Cornucopians: There is an abundance of resources and even where we exceed capacity using technology we can overcome limitations - "Good Anthropocene"
* Ecomodernism
    + "we affirm one long-standing environmental ideal, that humanity must shrink its impacts on the environment to make more room for nature, while we reject another, that human societies must harmonize with nature to avoid economic and ecological collapse."
    + "Intensifying many human activities — particularly farming, energy extraction, forestry, and settlement — so that they use less land and interfere less with the natural world, is the key to decoupling human development from environmental impacts. These socioeconomic and technological processes are central to economic modernization and environmental protection. Together they allow people to mitigate climate change, to spare nature, and to alleviate global poverty. Although we have to date written separately, our views are increasingly discussed as a whole. We call ourselves eco-pragmatists and ecomodernists. We oﬀer this statement to aﬃrm and to clarify our views and to describe our vision for putting humankind’s extraordinary powers in the service of creating a good Anthropocene.” 


### Debrief

Go over your notes & briefly answer these questions:

*	What was the most muddy concept(s)? Do we need to further clarify?
*	What was the exciting, interesting, or a new concept you learned?
*	Was there any “assumed background knowledge” you didn’t have? Do we need to further clarify?
*	Any additional general comments or questions on today's lecture or this week’s lab?

Submit your answers [`r icon::fa("clipboard-list")`](https://docs.google.com/forms/d/e/1FAIpQLSf_wpIenOLXtsZ24-3Aa120mgZmN3ioZHVkA342ZCYOj5OQug/viewform?usp=sf_link).


<br>

**Due by 3pm the day after lecture.**


### Dig a little deeper

Additional resources:

`r icon::fa("book-reader")` Schellenberg, ["On Behalf Of Environmentalists, I Apologize For The Climate Scare"](https://environmentalprogress.org/big-news/2020/6/29/on-behalf-of-environmentalists-i-apologize-for-the-climate-scare)

`r icon::fa("book-reader")` Gleick, ["Book review: Bad science and bad arguments abound in 'Apocalypse Never' by Michael Shellenberger"](https://yaleclimateconnections.org/2020/07/review-bad-science-and-bad-arguments-abound-in-apocalypse-never/)

`r icon::fa("book-reader")` Schellenberg, ["Bad science and bad ethics in Peter Gleick’s Review of “Apocalypse Never” at Yale Climate Connections"](https://environmentalprogress.org/big-news/2020/8/3/bad-science-and-bad-ethics-in-peter-gleicks-review-of-apocalypse-never-at-yale-climate-connections)

