---
title: "Conservation Biology (BI328)"
description: | 
  Fall 2020 Lectures
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

```

# Species-level conservation

### Assigned readings

**Reading reflections due: Oct. 16th, 5pm**

`r icon::fa("book-reader")` Cardinale et al. 2019. **Conservation Biology**. Chapter 16


*Food for thought*

Consider pros and cons of zoos and aquariums by necessity keeping animals in captivity. Do you object on principle or do you think that the "how" is important? 


<br>

**Reading reflections due: Oct. 23rd, 5pm**

`r icon::fa("book-reader")` Cardinale et al. 2019. **Conservation Biology**. Chapter 13

`r icon::fa("book-reader")` Lacy (2019) Lessons from 30 years of population viability analysis of wildlife populations. Zoo Biology 38:67-77.

*Food for thought*

Consider the pros and cons of relying on models for much of the decision-making process.


<br>

**Reading reflections due: Oct. 30th, 5pm**

`r icon::fa("book-reader")` Hedrick & Fredrickson (2010). Genetic rescue guidelines with examples from Mexican wolves and Florida panthers. Conservation genetics, 11(2), 615-626.

`r icon::fa("book-reader")` Schwartz et al. (2007). Genetic monitoring as a promising tool for conservation and management. Trends in ecology & evolution, 22(1), 25-33.

*Food for thought*

Conservation genetics is used as both a tool to support traditional approaches and to understand (and avoid) the impact of loss of genetic diversity itself.

Re-consider the parameters a population viability analysis needs to consider including conservation genetics goals.


<br>

### Outline

**Wildlife Trade**

* Global wildlife trade is a multibillion dollar industry
    + wide array of species (25% of terrestrial species affected)
    + impacts of trade concentrated in certain phylogenetic groups leading to potential for substantial long-term impact on certain lineages
    + Wildlife trade richness & hotspots of wildlife trade concentrated in tropics
* Legal Wildlife trade
    + Primates
    + wild-caught fish + coral
    + Main exporters: South East Asia & Amazon
* Is (legal) wildlife trade sustainable?
    + many species can be sustainably exploited resulting in potential for sustainable commercial trade
    + uncontrolled trafficking/overexploitation can result in serious threat to local populations
* Regulating the wildlife trade (CITES)
    + Multilateral treaty to protect endangered plants/animals by regulating unsustainable wildlife trade
    + Signatories voluntarily adopt their own domestic legislation
    + demand is met by captive breeding/farming, harvesting from the wild and illegal harvesting/poaching
    + lack of monitoring & enforcement are major contributors to resulting illegal trade
* Illegal wildlife trade
    + Primary driver of illegal trade is black market prices for rare specimen & body parts used for traditional medicine, folk remedies, status symbols, collector items
    + global problem but major concentration in South Africa & Southeast Asia
    + mammals/mammal derivates 51% of all seizures: skins, pelts, furs (26%) and ivory (25%) make up half of seized mammal derivates
    + 76% of seizures included species listed on CITES Appendix I or II
    + Orchids represent > 70% of 30,000 CITES-listed species 
    + organized crime create international trafficking networks to fund illegal hunting, trapping & smuggling of high values wildlife
* How can we combat illegal wildlife trade?
    + poaching is more than an enforcement problem
    + huge economic disparity between key markets & primary source countries makes illegal trade lucrative (if risky) source of income
    + enforcement involves a cost/benefit analysis of conservation vs poaching (turn poachers into protectors)
    + mitigating wildlife trade can be achieved by increasing enforcement or decreasing demand
    + illegal trade can be combated by promoting sustainable trade
* Wildlife forensics are a valuable tool to enforce regulations
    + Wildlife trade and fraudulence in food, artefacts, and cosmetic industries may impact wildlife
    + Lack of proper tools to identify & trace products (species/region of origin) can be a major constraint to frame charges against poachers/smugglers by law enforcement
    + wildlife forensics methods must be fast, accurate & reliable with comprehensive coverage/easy accessibility to aid criminal investigation processes

**Ex situ conservation**

* Ex situ conservation can contribute to in situ conservation strategies.
* Zoos & Aquariums
    + Animals/fish are housed in human-built enclosures and displayed to the public may also be used for research and/or breeding programs
    + Threatened animal species can find temporary refuge in zoos/aquariums
    + some species are extinct in the wild but extant specimen exist in captivity
    + criticism of zoos include concerns of ethical welfare of animals and that money would be better spent if directly used for conservation
    + Zoos are addressing points of critisicm and re-inventing themselves as conservation centers
* Botanical Gardens/arboretums
    + Botanical gardens are dedicated to the collection, cultivation, and preservation of plants – may contain specialized collections of specific plant groups or represent biomes
    + Arboretum specialized collection of woody plants/trees
    + Purpose: Curation of medical plants, Taxonomy/collections for research programs, Assist in propagation & dissemination of plants for horticulture, agriculture, forestry, landscaping, restoration efforts, industry
* Gene and Seed banks are biorepositories preserving genetic material
    + Frozen zoos collect & hold tissues, cells, gametes & DNA of endangered animals in cryogenic freezers to assist with reproduction through artificial insemination, in vitro fertilization, and cloning (future plans).
    + Seed banks stock & preserve seeds that can be germinated later to produce new plants.
Most seeds can be stored for extended periods in cold/dry conditions at low cost with minimal supervision
* Contributions to in situ conservation
    + Captive breeding programs
    + reintroduction/reinforcement
    + education & public outreach
    
**Species-level conservation**

* primary goal of species-level conservation is to ensure persistence of a species
    + after threats are identified & removed where possible tit needs to be ensured tha the remaining population(s) are sufficiently large to persist
    + to ensure long-term viability a populations must have Sufficient individuals in population to survive & reproduce to maintain positive growth rate and sufficient genetic diversity in population to maintain adaptive potential & avoid inbreeding depression
    + populations may be restored using assisten colonization, reintroduction, and augmentation strategies
* Decision-making and trade-offs
    + every conservation effort has trade-offs (ecological, economic, social)
    + every implemented conservation action is one of a suite of possible actions
    + Structured decision-making offers a transparent and data-driven framework to evaluate potential decisions for management of natural resources 
* Strategic species conservation
    + Surrogate species provide an efficient means for achieving broader conservation goals
    + Flagship species is used to attract the attention of the public (usually about the plight of a specific ecosystem or region)
    + Umbrella species provides protective umbrella that benefits other species (usually large home range)

**Estimating population size**

* Census
    + Count number of individuals present in a populations and monitor changes using repeated census over successive time intervals
    + limitations of census include that they are frequently not repeated and that a census should be a complete count but rarely actually is
    + Census of a biological community or geographic region determines what species are currently present in a locality
    + Temporal and spatial comparisons enable us to understand changes in geographic ranges & local abundance
    
* Mark-recapture
    + Individuals of a population are caught & marked during first sampling period
    + During second sampling period the number of recaptured individuals are recorded
    + Abundance is estimated based on the ratio of recaptured animals to total animals captured during second period

* Population models
    + Models allowing us to estimate population change over time are an important conservation tool to simulated how changes in a landscape may impact populations
    + Models are (over)simplifications and based on best available sample information (frequently approximations)
    + Changing conditions (habitat fragmentation, change in periodicity of weather events, environmental change) are more or less straightforward to model
    + Population growth models: geometric growth, exponential growth, logistic growth.
    + Age/stage-based models estimate fecundity and survival probability by age classes/life stages and allows for better understanding of demographic structure (number of individuals at each life stage/year class)
    + Deterministic models have fixed values (constants) that reflect average values across life stages 
    + Stochastic models account for variation in model parameters among time points
    
**Minimum viable populations** 

* Minimum viable population size
    + smallest population size predicted to have high chance of persisting for a set period of time 
    + management goal: determine the minimum number of individuals necessary to ensure long-term survival of a population/species
    + underlying fundamental principle is to be able to account for harsh not average conditions (run models for a range of scenarios)
    + empirical evidence for MVP from monitored populations
    + there is no magic number that can be applied to every species but there are consistent patterns
    + accurate estimates require detailed demographic studies and analysis of the effect of the environment
    + mobility/recolonization ability allows for lower MVPs
    + life-history parameters/intrinsic growth rate have strong effect on MVP sizes

* Minimum dynamic area/minimum area required
    + area of suitable habitat necessary to maintain MVP
    + factors determining minimum area required: body mass, feeding guild/trophic level, home range/dispersal distance, demography, niche breadth/proximity to range boundary
    
* Population viability analysis
    + Population viability analysis is a risk assessment used to determine the minimum viable population and/or minimum required area needed for a population to be able to persist 
    + need estimates of current population size, data/model to estimate how pop size will change over time to determine probability of population going extinct in certain time period
    + example of PVA using stochastic geometric growth model: use basic growth model to predict population size each year for 50 years drawing growth rate from distribution of past annual growth rates to include stochasticity; each run will yield different result to determine extinction probability
    + Increase usefulness of analysis by simulating different management plans and environmental scenarios  
    + PVAs are population-specific and should be built using population-specific birth/death/growth rates
    + Models become increasingly complex & accurate the better we understand the ecology, threats, demography of a species
    + Models are only as good as the data that goes into them: Range of parameters for birth/death/growth rates by age/life stages based on past monitoring vs assumptions
    + Assumption that past data predicts future variability: Create a range of possible future scenarios to be able to make predictions about future viability
    + Validate models when possible: Use past data to compare to monitoring data
    + PVA can also be used to determine minimum require area
    + PVA can be used to inform management decisions using sophisticated models accounting for spatial distribution of habitat patches, dispersal corridors, abundance of tree cavities, forest dynamics

**The problem with small populations**

* Challenges to conserving small populations: Even when causes of population decline are removed and/or reduced small population still face three challenges that can lead to extinction
    + Demographic stochasticity caused by random variations in birth/death rates
    + Environmental stochasticity caused by variation in the biological/physical environment
    + Loss of genetic variability due to effects of genetic drift/inbreeding
* Environmental stochasticity
    + Variation in the biotic & abiotic conditions of a landscape  affects the birth & survival rates of a population
    + acts on a population level resulting in a shift in entire distribution/mean rates 
    + Natural catastrophes/disasters are a form of environmental stochasticity occurring at unpredictable intervals – even if probability per generation is low over time period of decades/centuries have high probability
    + Accounting for environm. stochasticity in management: reintroduced populations are small & isolated – probability of persistence can be improved by re-introducing at multiple spatially diverse sites 
* Demographic stochasticity
    + birth and death rate of each individual is a discrete and probabilistic event resulting in random fluctuations in population size
    + acts on an individual level/leads to random variation in birth/death rates the impact of variability increases as population size decreases
    + in small populations demographic stochasticity can lead to deviations in sex ratio resulting in further decrease in population size
* Allee effect
    + Allee effect is a population response due biological fitness of individuals being correlated with population size/density
    + if population growth rate falls below certain critical threshold, fitness of individuals dramatically decreases & may cause population to crash
    + Allee effects can be caused by: Unequal sex ratios, loss of heterozygosity due to inbreeding, reduction in cooperative interactions
* Genetic stochasticity
    + acts on genetic diversity of a population: genetic drift and inbreeding are inversely correlated to population size
    + must maintain sufficient number of individuals to avoid genetic drift and inbreeding and maintain sufficient genetic diversity in population to maintain adaptive potential & avoid inbreeding depression

**Loss of Genetic Diversity (Conservation Genetics)**

* Characterizing genetic diversity
    + a locus is a specific position on a chromosome – this can be a gene (coding DNA) or a different genetic marker (non-coding DNA)
    + A polymorphism is a genetic variation resulting in different variations (alleles) of the same locus
    + Higher levels of heterozygosity among loci within an individual and across loci in a population indicate higher levels of genetic diversity in a population
    + Hardy-Weinberg Equilibrium describes the relationship of heterozygosity & allele freq. which allows us to understand whether genetic diversity is higher/lower than expected 
    + Hardy-Weinberg Principle: Genetic diversity remains constant from one generation to the next assuming no mutation, no selection, no drift, no gene flow & random mating
* Loss of genetic diversity
    + Genetic drift and Inbreeding result in a loss of heterozygosity & allelic diversity 
    + both processes are inversely correlated to population size 
    + Impacts on a population are Inbreeding Depression (short-term impact) and Loss of Adaptive Potential
(long-term impact)
* Conservation of adaptive potential is important for the long-term persistence of a (small) population especially under changing conditions
    + The genetic diversity of a population harbors the adaptive potential of a population: the ability to adapt to a changing environment
    + Selection acts on standing diversity: individuals in the same population may have different alleles at the same gene
Individuals with certain (combinations) of alleles may have genotypes and corresponding phenotypes needed to survive & reproduce under future new conditions
* Genotype - Phenotype - Environment interaction
    + Genotype of an individual consists of both coding and non-coding parts of the genome that determine phenotype of an individual
    + The phenotype of an individual consists not just of the morphology of an individuals but also it’s physiology and behavior
    + Individuals with the same phenotype may differ in their genotypes.
     + Changes in the environment can alter the expression of genes (phenotypic plasticity) which means two individuals may have the same genotype but vary in their phenotype depending on the environmental conditions/stimuli.
    + The fitness of phenotypes is determined by the selective pressures produced through environmental conditions (i.e. the same phenotype may have different levels of fitness under different environmental conditions)
    + environmental pressures include biotic factors (e.g. species interactions) and abiotic factors (e.g. temperature, salinity)
    + We expect phenotypes with the highest fitness and their associated genotypes to be the most common in a population.
    + changes in the environment will create new selective pressures in a system that was previously at equilibrium with individuals well adapted to previous conditions.
    + This is expected to result in the fitness level of certain phenotypes increasing or decreasing. 
    + Some phenotypes might no longer be able to survive under new conditions and the genotypes associated with them would be lost from the gene pool while genotypes associated with increased fitness would be come more common.
* Genetic drift
    + The gene pool is the sum of a population's genetic material at a specific point in time, it includes all genes and combinations of alleles 
    + genetic drift is random changes in allele frequencies due to sampling error and is random in respect to fitness
    + the probability of an allele becoming fixed/lost is the frequency of an allele at a given point in time
    + the expected number of generations to fixation is proportional to population size
    + rare alleles are lost first; as a consequence individuals mating are more likely to have the same genotype resulting in excess homozygosity
    + sufficiently large populations act as “infinite populations” (drift is negligible)
  * Genetic drift increase the genetic load and results in a loss of adaptive potential
    + small populations more likely to loose allele entirely due to genetic drift: once alleles are lost, they cannot be returned to the gene pool
    + recessive alleles representing loss-of-function mutations are usually rare and exist only in heterozygote individuals in small populations experiencing loss of genetic diversity and increasing homozygosity due to drift these traits are now expressed lowering the fitness of individuals
    + most genes are under selection for heterozygote advantage (selection favors genetic diversity) - drift increase homozygosity and alleles are lost
* Genetic bottlenecks accelerate the loss of genetic diversity
    + Population bottleneck occurs when a population size is drastically reduced for at least one generation
    + loss of diversity due to reduction individuals (randomly “selected”)
    + rare alleles have high probability of being lost
    + while the population is small it is highly susceptible to drift & risk of inbreeding
    + Northern elephant seals have much lower genetic diversity 
compared to southern elephant seals as a result of a demographic bottleneck
    + The Tasmanian Devil experienced a demographic and genetic bottleneck which greatly reduced their genetic diversity; genetic diversity remained low and made them highly susceptible to transmitted facial tumor disease which is now threatening the population with extinction.
* Founder effect
    + Immigrants from a source population establish a new population which is likely to have different allele frequencies compared to the population due to stochasticity of "randomly selecting" founding individuals
    + Re-colonization efforts are a population management strategy and managers must consider founder effects and negative consequences to be successful.
* Inbreeding increases levels of homozygosity
    + Inbreeding occurs when two individuals mate that have more similar genotypes than if they were randomly paired 
    + Inbreeding change genotype frequencies resulting in an excess of homozygotes in the population
    + mating of closely related individuals may result in a loss of biological fitness due to lower reproductive and/or survival rates of offspring (inbreeding depression)
    + Inbreeding can cause an allee effect (biological fitness of individuals are correlated with population size/density) resulting in negative population growth at low population densities
* Conservation Genetic of Prairie Chicken
    + endangered due to habitat loss/fragmentation resulting in small, genetically isolated populations
    + Loss of genetic diversity due to genetic drift & inbreeding resulted lower fertility and lower rates of successful egg hatching 
    Loss of genetic diversity due to genetic drift & inbreeding resulted lower fertility and lower rates of successful egg hatching 
    + Successful strategy to avoid inbreeding depression/loss of genetic diversity: Results in increased in population size & restoration of egg viability
* Extinction Vortex
    + positive feedback loops amplifying the negative effects of small populations can accelerate the reduction in population size and result in local extirpations
    + Genetic drift results in fixation of (deleterious) alleles reducing mean population fitness (genetic load)
    + Increasing probability of related individuals mating increasing the level of homozygosity and inbred individuals with lower fitness (inbreeding depression)
      + Mean population fitness reduced resulting in further decline of the population size, exacerbating problems causing population decline
* Effective population size






    

    



    



### Debrief

Go over your notes & briefly answer these questions:

*	What was the most muddy concept(s)? Do we need to further clarify?
*	What was the exciting, interesting, or a new concept you learned?
*	Was there any “assumed background knowledge” you didn’t have? Do we need to further clarify?
*	Any additional general comments or questions on today's lecture or this week’s lab?

Submit your answers [`r icon::fa("clipboard-list")`](https://docs.google.com/forms/d/e/1FAIpQLSf_wpIenOLXtsZ24-3Aa120mgZmN3ioZHVkA342ZCYOj5OQug/viewform?usp=sf_link).


<br>

**Due by 3pm the day after lecture.**


### Dig a little deeper

Additional resources:

`r icon::fa("book-reader")` Scheffers, Brett R., et al. "Global wildlife trade across the tree of life." Science 366.6461 (2019): 71-76.

`r icon::fa("book-reader")` Nijman, V. (2010). An overview of international wildlife trade from Southeast Asia. Biodiversity and conservation, 19(4), 1101-1114

`r icon::fa("book-reader")` Hinsley, et al. (2018). A review of the trade in orchids and its implications for conservation. Botanical Journal of the Linnean Society, 186(4), 435-455.

`r icon::fa("book-reader")` Challender & MacMillan (2014). Poaching is more than an enforcement problem. Conservation Letters, 7(5), 484-494.

`r icon::fa("book-reader")` Cooney et al (2017). From poachers to protectors: engaging local communities in solutions to illegal wildlife trade. Conservation Letters, 10(3), 367-374.

`r icon::fa("book-reader")` Holden et al. (2019). Increase anti‐poaching law‐enforcement or reduce demand for wildlife products? A framework to guide strategic conservation investments. Conservation Letters, 12(3), e12618.

`r icon::fa("book-reader")` Gouda, Sushanto, et al. "Wildlife forensics: A boon for species identification and conservation implications." Forensic Science International (2020): 110530.

`r icon::fa("book-reader")` Leader-Williams (1990). Black rhinos and African elephants: lessons for conservation funding. Oryx, 24(1), 23-29.

`r icon::fa("book-reader")` Traill et al. (2010). Pragmatic population viability targets in a rapidly changing world. Biological Conservation, 143(1), 28-34.

`r icon::fa("book-reader")` Wang et al (2019). Minimum viable population size and population growth rate of freshwater fishes and their relationships with life history traits. Scientific reports, 9(1), 1-8.

`r icon::fa("book-reader")` Shoemaker et al. (2013). Reexamining the minimum viable population concept for long‐lived species. Conservation Biology, 27(3), 542-551.

`r icon::fa("book-reader")` Pe’er et al. (2014). Toward better application of minimum area requirements in conservation planning. Biological Conservation, 170, 92-102.

`r icon::fa("book-reader")` Linda et al. 2020 Spatial and temporal dynamics of habitat availability and stability for a critically endangered arboreal marsupial: implications for conservation planning in a fire-prone landscape.

`r icon::fa("book-reader")` McCallum, H. (2008). Tasmanian devil facial tumour disease: lessons for conservation biology. Trends in ecology & evolution, 23(11), 631-637.

`r icon::fa("book-reader")` Hedrick & Fredrickson (2010). Genetic rescue guidelines with examples from Mexican wolves and Florida panthers. Conservation genetics, 11(2), 615-626.

`r icon::fa("book-reader")` Schwartz et al. (2007). Genetic monitoring as a promising tool for conservation and management. Trends in ecology & evolution, 22(1), 25-33.

`r icon::fa("book-reader")` Johnson, Warren E., David P. Onorato, Melody E. Roelke, E. Darrell Land, Mark Cunningham, Robert C. Belden, Roy McBride et al. "Genetic restoration of the Florida panther." Science 329, no. 5999 (2010): 1641-1645.





### Review

* Give a brief description of what the wildlife trade is and what range of products it encompasses.
* List two regions that are main exporters in the wildlife trade and explain why they are well-suited to be so.
* The Amazon is one of the main exporters in the wildlife trade. Use three examples to describe the range of how animals are sourced, where they are exported to, and for what purpose.
* Discuss whether the legal wildlife trade is/can be sustainable and give specific arguments to why having a well-regulated, sustainable trade commercial trade of wildlife is important.
* Discuss how uncontrolled trafficking of wildlife can result in a serious threat to local animal/plant populations.
* Give a brief explanation of what CITES is and what it means for species to be listed on Appendix I, II, or II.
* Give a brief description of the legal and illegal wildlife trade in terms of components of supply, trade, and demand.
* Describe the primary driver of illegal wildlife trade.
* Give a brief overview of the players & processes involved in wildlife trafficking. Argue why it is most frequently run by crime syndicates.
* Give a simple "equation" that can be used to determine the cost/benefit analysis of conservation vs poaching and explain how it can be used to optimize management strategies.
* Explain how using enforcement as the main tool to stop illegal wildlife trade can have unintended consequences.
* List a range of possible strategies to combat the wildlife trade.
* Compare and contrast using campaigns geared toward reducing prices and demand, promoting sustainable trade, and enforcement of regulations (consider limitations and benefits of each).
* Describe what strategies can be used to reduce motivation for criminal involvement in the wildlife trade.
* Strategies can be categorized as long-term vs. short-term and targeting the causes and/or the "symptoms" of the illegal wildlife trade. List a range of strategies and describe the tools used to achieve them and explain whether they are short/long-term strategies and whether they are focused more on the causes or effects of illegal trafficking.
* Give a brief description of what wildlife forensics is and explain why it is an important tool to enforce regulations.
* Explain the difference between *in situ* and *ex situ* conservation strategies.
* Give a brief definition of what *ex situ* conservation is, list the major groups of *ex situ* conservation facilities and explain how they can contribute to in situ conservation.
* Give a brief definition of what a zoo or aquarium is.
* Give a brief description of the three major criticism levied against zoos/aquariums.
* Explain what it means for a zoo to reinvent itself as a conservation center.
* Give a brief description of what a botanical garden and an arboretum is and their purpose and explain how they can support in situ conservation.
* Give a brief description of what gene and seed banks are and explain how they can be used to support in situ conservation.
* Briefly explain why seed banks are particularly important for the agricultural industry.
* List the three main categories of how *ex situ* conservation facilities can contribute to *in situ* conservation.
* Give a brief explanation of what a captive breeding program is and explain why zoos/aquariums/botanical gardens are especially well-suited to be used to develop them.
* Give a brief explanation for the three main reproductive tools & techniques used to increase reproductive output in captivity and explain why they are especially helpful for endangered/threatened species.
* Give a brief definition of what cloning and de-extinction technology is and argue whether or not you think it is a good idea to use as a conservation tool.
* List the five main limitations of captive breeding programs and discuss three of them in detail (remember discuss means that you need to describe them too).
* Compare and contrast strategies of reintroduction/reestablishment and reinforcement/augmentation and explain how they differ from introduction/translocation/assisted colonization.
* List three strategies used to increase the success of captive breeding programs and describe two of them in more detail.
* Give two arguments as to whether zoos/aquariums are good education/outreach tools and discuss whether you think zoos are effective in their mission statement in that regard.
* State the primary goal of species-level conservation.
* The primary goal of species-level conservation is to ensure the persistence of a species. Briefly explain the two main components dictating how large a population must bee to ensure long-term viability and list three options to restore populations that are currently too small.
* Give a brief explanation of what structured decision-making is.
* Explain what the main components of a cost-benefit analysis (e.g. single multi-attributed rating technique (SMART)) to determine the most appropriate management strategy are are to argue the benefits of this type of decision-making process especially when there are multiple stakeholders involved in the decision-making process.
* Explain what a surrogate species is and give brief descriptions of two types of surrogate species.
* List the two main methods to estimate population size and discuss their limitations.
* Briefly describe characteristics of a species that would make them more or less difficult to count using the census method.
* Discuss limitations of the census method.
* Explain the benefits of repeated censuses of biological communities and geographic regions.
* Explain how mark-recapture can be used to determine the number of individuals in a population.
* List processes that can increase and decrease the number of individuals in a population.
* Explain what a closed and an open population is and explain how this effects the processes that increase/decrease individuals in a populations.
* Compare and contrast the three major population models in terms of whether growth is constrained/unconstrained, time is modeled as discrete or continuous, and whether the growth rate changes over time. For each model determine a group of species this model should be applied to.
* An invasive weed has been detected and managers want to project how quickly it will establish and spread. This weed flowers and disperses seeds once a year. Argue which would be the most appropriate basic population growth model to apply.
* A small (but adorable) species of mice has recently experienced a decline due to a loss of their main food source. They reproduce continuously throughout the year, have large litter sizes, and individuals mature within a few months, so managers are not too concerned. However, because they are an important food source for several endangered species at higher trophic levels they want to model their population growth to recovery. Argue which fundamental population growth model is the most appropriate to use.
* A small number of elephants have recently been relocated to a newly established sanctuary. Because elephants mature late and have few offspring with high parental care most of the elephants in the "starter population" are mature adults or sub-adults. Argue which fundamental population growth model is the most appropriate to apply to determine how the population size will change in the near future.
* Explain how age/stage-based models differ from standard geometric/exponential/logarithmic growth and why they are a better approximation and more informative for conservation/management.
* Use a specific example to explain how stage/age-based demographic models can be used to optimized conservation strategies.
* Explain the difference between a deterministic and a stochastic model.
* A coastal fish population is being assessed for a new fisheries management plan. Since this is a well understood species we have monitoring data from the last 40 years that include detailed information on the approximate number of eggs laid and larvae hatched, how many yearlings settle in the bays, how many sub-adults migrate back out to see and the number of adults in different year classes for each year. We also know from a previous study that even though they mature at 3 years old, the female's fecundity steadily increases for about 5 years before it levels out. By contrast, a second fish species has a similar age-at-maturity but is more evasive and therefore we only have information on overall population size (large juveniles, subadults + adults) from year to year. For each species argue what type of model would be the most appropriate to use to get the best population projections possible.
* Give a definition for the concepts of minimum viable population size and minimum required area/minimum dynamic area.
* Define what a minimum viable population size is and explain why it is so important for effective species-level management.
* Argue the limitations and benefits of having to determine a MVP for each specific population targeted for management/conservation compared to having a rule of thumb to apply across species. Argue whether you think it is even possible to determine a "magic number" (median MVP) across (groups of) species.
* Explain how characteristics such as mobility/dispersal ability affect MVP estimates.
* Explain how life-history impacts MVP impacts.
* Consider a small mammal that matures quickly and has a high fecundity compared to a long-lived large-bodied mammal with a long generation time and few offspring with high parental care and argue which you think will have the larger MVP. 
* Occasionally small populations of long-lived species are observed to persist for extended periods of time. Explain how this is possible despite our general understanding of the MVP concept and argue whether you think this is common enough that managers should rely on this effect for their management plans.
* Briefly describe the concept of a minimum dynamic area (minimum required area) and argue whether small mammals or large carnivores are expect to have larger/smaller minimum dynamic area.
* List factors that can determine the minimum area required for a population to persist. Choose to an explain how they affect the area needed.
* Give a brief description of what a population viability analysis is (this should include the purpose and components involved).
* You have just been given 50 years worth of monitoring for a isolated population of elk in a national park that breeds every Fall. Give a brief description of how you would make best use of this data and what you know about population growth models to determine the probability of extinction in 50 years. Your description should should include a description of what type of model you will use, whether it is stochastic or deterministic, and the individual steps involved to determine extinction probability.
* Briefly outline the limitations and potential of PVA models.
* Explain why it can be useful to create PVAs focused on habitat and not just population size and argue which you think is more useful for management decision making.
* Explain why population monitoring programs and the data they can generate are important even for species that currently aren't endangered in the connection of PVA models.
* Give a brief description of the three main challenges small populations face that can lead to extinction.
* Explain what environmental stochasticity is and how it can contribute to population extinction.
* Briefly describe an example of how environmental stochasticity can be accounted for in management strategies.
* Explain what demographic stochasticity is and how it can contribute to population extinctions.
* Compare and contrast demographic and environmental stochasticity.
* Define what the Allee effect is. List the three main causes for Allee effects and use an example to explain one in detail.
* List the two processes that lead to a loss of genetic diversity. For each list the main consequence and categorize it as a short or long-term impact.
* Briefly explain what adaptive potential is and why it is important to consider for conservation & management.
* Explain the relationship between genotype, phenotype, environmental conditions and selection and use this to explain why the genetic diversity of a population harbors the adaptive potential of that population.
* Give a brief explanation of the process of genetic drift and describe how it can lead to a loss of genetic diversity.
* Explain why even though every population experiences genetic drift it is only a problem in small population from the perspective of conservation genetics.
* Use brief descriptions of the concepts of "genetic (mutational) load" and "adaptive potential" to assess the short and long-term impacts of the loss of genetic diversity.
* Describe what a genetic bottleneck is and give a brief explanation of how it contributes to and accelerates the loss of genetic diversity.
* Northern Elephant seals are observed to have much lower genetic diversity compared to Southern Elephant seals even though both species have similar population sizes. Argue what two type of past event(s) could have contributed to this pattern.
* Use the example of the Tasmanian devil and the Tasmanian devil facial tumor disease to explain how a population bottleneck can result in the loss of adaptive potential and how this can have long-term impacts on the persistence of a population even after population sizes increase.
* Give a brief description of the founder effect, explain how it can effect genetic diversity, and how conservation strategies may inadvertently cause a founder effect.
* Briefly describe what inbreeding is and how it affects genetic diversity.
* Briefly describe what inbreeding depression is.
* Use inbreeding depression to explain what the allee effect is and why this can be problematic for conservation and management in the context of population viability analyses (this includes defining inbreeding depression).
* Use an example to explain the concept of an extinction vortex.
* Define census population size, number of spawners, effective population size, and effective number of breeders.
* Compare and contrast census and effective population size to explain how these are informative for conservation & management and what their potential limitations are.
* List the three main factors resulting in the effective population size being smaller than the census population size.
* Briefly explain why the age structure impacts the effective population size.
* Briefly describe how the sex ratio impacts the effective population size.
* Briefly explain how high variance in reproductive success impacts the effective population size.
* The effective population size can be up to three to five orders of magnitude smaller than the census population size in marine fish that are broadcast spawners and type III survivorship resulting in high variance in reproductive success. Explain why not accounting for the Ne/Nc ratio can be problematic in the context of population viability analysis.
* Give a brief explanation of what genetic rescue is.
* Briefly describe the scenario, necessary components, and information needed to be able to apply genetic rescue as a management option.
* Explain why it is so important to implement a long-term monitoring plan along with a cautionary translocation protocol by briefly outlining the limitations and potential negative impacts of genetic rescue.
* Use a specific example to define the specific goals of genetic rescue, when it can/should be implemented and specific parameters you can use to test whether the management plan is successful.
* Briefly discus the limitations and possible negative consequences of genetic rescue.
* Conservation implies a goal of preserving a species (population). Argue whether given this prerogative genetic rescue should be considered a "conservation" strategy.
* A population of previously wide-spread foxes now consist only of a small, isolated breeding population. Recently, physical deformities have been commonly observed in the few juveniles that are found. Give a brief explanation of what could be causing this and suggest a way to test if your assumption is correct. Briefly outline a strategy you could use to counteract these effects, including what you would need to allow you to implement this strategy, how you would implement it, and how you would measure your success.



<br>

Download a hard copy of the recap questions [`r icon::fa("file-download")`](files/BI328_ReviewQs_SpeciesConservation.pdf).
