---
title: "Conservation Biology (BI328)"
description: | 
  Fall 2020 Lectures
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

```

# Ecosystem & Landscape-level conservation

### Assigned readings

**Reading reflections due: Nov. 13th, 5pm**

`r icon::fa("book-reader")` Cardinale et al. 2019. **Conservation Biology**. Chapter 14

`r icon::fa("book-reader")` Cardinale et al. 2019. **Conservation Biology**. Chapter 15


*Food for thought*

* Why do you think historically conservation focused more on the species-level?
* Do you think focusing on the minimum viable population or the minimum required habitat is more effective?
* Why do you think it can be more difficult to engage the public in a campaign to conserve a specific endangered species compared to implementing protected areas?


<br>


### Outline

**Preserving Habitat**

* Ex situ and in situ strategies focus on conserving small populations
    + natural environment (long-term strategy)
    + artificial environments (short-term solutions) to enhance/kick-start in situ strategies
* Challenges to conserving small populations even after all threats have been removed
    + demographic perspective: focus on positive growth rates
    + genetic perspective: focus on avoiding inbreeding depression (short-term) and loss of adaptive potential (long-term)
* Focus on preserving complete ecosystems and their functions
    + importance of maintaining and conserving habitat for species-focused conservation
    + some species function as umbrella species protecting species that inhabit the same territory/ecosystem being protected
    + focus on conserving fully functioning ecosystem
    
**Classification of Protected Areas**

* IUCN Classifications
    + Category Ia: Strict Nature reserve/Ib Wilderness area: created/managed for protection of large/unspoiled wilderness areas to protect & maintain biodiversity & evolutionary ecosystem processes
    + Category IIb: Management focused on balancing conservation with human tourism/recreation which includes some development (economic benefit surrounding communities)
    + Category III: Protect specific natural geological/geomorphological features, culturally influenced natural features, or cultural sites w/associated ecology
    + Management focused on maintaining, conserving, or restoring species and habitats, includes public outreach/providing means for urban residents obtain contact with nature
    + Category V: Management focused on protecting important landscapes & sustain associated nature conservation/other values by interactions w/humans & traditional managem. practices
    + Category VI: Management focused on protecting natural ecosystems & natural use of resources when conservation + sustainable use mutually beneficial
* Purpose, Focus, and Objectives of creating protected areas
    + strict natural reserve: no human development or exploitation
    + (eco)tourism, recreation. outreach, cultural significance
    + Resource management: balance conservation & sustainable exploitation
    + components considered: landscape/geological features, cultural significance, species/habitat
* Positive impacts on human well-being
    + Social, political, economic impacts of protected areas on human well-being: Particularly in developing nations protected areas may improve health & prosperity of local people through extraction, sale, and use of products from the protected area and as result of economic activity (ecotourism, recreation)
    + Economic benefits of protected areas translate into improved human health: Multiple use protected areas managed simultaneously for conservation & sustainable resources use improved people’s health & wealth compared to those not located near protected area
Strict areas showed no socio-economic benefits to local people
* Downside of protected areas
    + creation of protected areas may lead to a displacement of local communities/loss of livelihoods: Top-down decisions & enforcement (evicting people) from governments may lead to conflict & violence and/or loss of livelihood (agriculture, no access to land)
    + Displaced people rarely compensated and are usually more vulnerable (poor, no political representation): Implementation of conservation needs to account for (traditional) property & sovereignty rights and limitation of livelihoods & economic development of local communities
* Global status of protected areas
    + growth in area of coverage for protected areas and spatial distribution
    + key biodiversity areas “sites contributing significantly to global persistence of biodiversity”
    
**Approaches for choosing protected areas**

* Habitat requirement of a give species
* Hotspots of biodiversity
    + Biodiversity hotspot is a geographic area with particularly high levels and is also highly threatened by human activities
    + Goal: Protect a few, relatively small geographic areas and protect large fraction of world’s species
    + Limitations: delineation depends heavily on definition/measures of biodiversity, overemphasis on diversity may result in other conservation goals being overlooked (e.g. ecosystem services of systems that have naturally low diversity, for example seagrass beds, open oceans)
* Ecoregions
    + “a unit of land containing a distinct assemblage of natural communities and species, with boundaries that approximate the original extent of natural communities prior to major land-use change” 
    + Goal: Protect full representation of naturally occurring biological boundaries pre-anthropogenic impacts
    + Limitations: Overambitious goals, many countries have poor regulations & enforcement, degree of arbitrariness at which ecoregions are delineated, defined at scales that can be impractical to manage – need multiple countries to cooperate
* Political & economic boundaries
    + Organizations advocating for conservation that use political boundaries to plan & prioritize biodiversity conservation will better align with plans/actions of governments
    + Planning efforts of governments generally follow geopolitical boundaries not biological boundaries
    + Limitations: Species couldn't care less what political boundaries there are
* Ecosystem services
    + Goals: Select protected areas on their delivery of ecosystem services to protect biological functions of nature underlying delivery of important goods & services
    + Areas maximizing biodiversity (ecoregion approach) do not always maximize ecosystem services: distinct but potentially complimentary goals of protecting biodiversity
    + Least common approach but expected to increase as our understanding of ecosystem services increases
* Areas of cultural importance
    + Goal: Select protected areas according to their cultural importance or significance
    + Most typically obtain protection through UNESCO as Biosphere Reserves/World Heritage Sites
    
**Effectiveness of protected areas**

* Terrestrial protected areas
    + protected areas significantly reduce habitat loss & exhibit increased habitat cover: The magnitude of difference depends on the level of pressure on non-protected areas and whether there is continued pressure inside protected area
    + Large fractions of tropical forests already destroyed – sharp boundaries in forest cover at edges of protected areas
    + Protected areas on average 14% more individuals (population sizes larger)
    + Protected areas on average 11% higher species richness but adjusting for sample size/number of species, higher levels of endemism no longer significant, i.e. the benefit of protected areas frequently is larger populations not unique species
* Marine protected areas
    + Marine protected areas (MPAs) are a recent strategy most MPAs are small ( < 10km2) but initial success is promising in terms of effectiveness
    + MPAs reduce loss of important marine habitats
    + MPAs maintain higher population sizes and higher biodiversity of many species across biomes, different types of habitats, and geographic regions
* Predictors of success
    + Not all protected areas are effective/successful: only 22% of protected areas have sound management/50% of tropical reserves are effective, frequently documentation of declines in plant/animal abundance inside PA
    + Most common threats to PAs include illegal/unsustainable hunting (61%), disturbance from recreational activities (55%), natural system disturbances/fire/fire suppression (49%)
    + Strongest predictor of effective management is enforcement & compliance with regulations
    + successful PAs require public support from stakeholders & community involvement
    + Focus on integrated social development and conservation goals results in positive socioeconomic outcomes
    + Growing evidence that conservation efforts can be just as effective in multiuse PAs as in traditional strict PAs
    
**Landscape-level conservation**

* A landscape is a large geographic region spanning multiple biological communities & ecosystems which include different habitat types
* Habitat loss, fragmentation & degradation has resulted in landscapes mosaics/patch mosaics - Patches vary in quality, size, connectedness
    + Patches converted for human use (agriculture, urban)
    + heavily degraded patches (industrial pollution)
    + Natural habitat patches are small, fragmented, and disconnected
* need for landscape level conservation
    + Heterogeneous landscapes necessitates management at a landscape-level to maximize conservation of biodiversity/maintain natural habitats, the success of conservation efforts depends on ability to manage habitats surrounding protected areas/natural habitats
    + Human population density and habitat types quality are better predictors of success than size or other characteristics of PA
    + species migrate between habitats/patches for feeding/breeding or have large home ranges/territories necessitating conservation as network/at landscape level
    + Need to balance species conservation with ensuring the quality of life/human well-being: Integration of conservation & social development to create attitude stewardship/ownership as realize health/well-being tied to management of local ecosystems
* the goal of protected area networks is creating a collected of protected areas encompassing all scales of biodiversity that are collectively managed within a landscape
* Establishing new protected areas can focus on maximizing biodiversity conservation through individual PAs and/or optimizing biodiversity conservation across a landscape (PA network)
    + Select/design areas to be as large as possible (population size proportional to geographic area, Population size best predictor of persistence)
    + Select/design areas to minimize edge effects (shape, interior:edge ratio of patches)
    + Design areas with buffer zones to create gradient of protection (Multiuse habitat  with less restrictions on use)
    + Prioritize areas with irreplaceable/vulnerable species, communities, ecosystems (Value of rare, unique species/ecosystems that could be permanently lost)
    + Include not exclude humans from design of PAs: Excluding local communities/stakeholders has long-term negative impacts on success, instead integrate conservation & development projects to meet the needs of local communities
    + Design networks to maximize the number and/or area of PAs in a landscape: Species area relationship indicates initial rapid increase of species richness (large marginal return for adding PA) but slows down
    + Design networks to with PAs in close proximity linked to maximize connectivity and optimal dispersal for focal organisms
    + Design PA networks to conserve full range of biodiversity in the landscape
    + Manage PAs in the network as a whole: Importance of a consistent/coordinated plan (PAs may be owned/managed by different entities and exist across multiple jurisdictions and involve a range of stakeholders; focus on co-design/participatory design of networks)
    
**Managing unprotected areas**

* unprotected areas can/should be managed in the context of integrated network of protected areas
    + Reality Check: 85% of land/92% of ocean currently unprotected – majority of land/water will remain unprotected and a large fraction of species not covered by PAs/many endangered/rare species exist only on private land
    + Realistic Assessment: Many habitats are suboptimal but may still serve as viable habitat for species, management & conservation plans should include/account for unprotected areas
* Managing unprotected areas focusing on sustainable use can benefit biodiversity
    + Forests selectively logged on long-cutting cycles or cut for farming using traditional shifting method can maintain high habitat quality/ecosystem services
    + large tracts of land for may be owned as personal estates and/or for private hunting encouraging private landowners to protect rare species/ecosystems as long-term strategy
    + Urbanization is “last step” of land conversion, but some native species have adapted to urban habitats: green spaces, urban streams/ponds, golf courses, infrastructure
    + Agricultural habitat less diverse than natural systems it replaces but some farming practices are more sustainable than others - Agroecological farming emphasizes integrating farms into landscapes designed to sustainably conserve/manage natural resources
* Multiuse/mixed-use habitats are managed for multiple purposes
    + Multiple use/mixed use habitat are large parcels of (government-owned) land managed to provide variety of goods & services
    + Consider trade-offs of alternative development options (environmental/socioeconomic) 
    + Prevent (government-) approved activities on public lands threatening biodiversity using regulations, legal system, political pressure
* Ecosystem-based management
    + “Ecosystem-based management is an integrated approach to management that considers the entire ecosystem, including humans. The goal of ecosystem-based management is to maintain an ecosystem in a healthy, productive, and resilient condition, so that it can provide the services humans want and need. Ecosystem-based management differs from current approaches that usually focus on a single species, sector, activity or concern; it considers the cumulative impacts of different sectors.” Communication Partnership for Science and Sea (COMPASS)
    + EBM can work on a continuum of management levels/ecosystem components managed as intrinsically linked
    + Place-based: geographic areas defined by ecological criteria (not political boundaries)
    + Proactive: incorporate trade-offs to manage (marine/coastal) environments
    + Cross-sectoral: considers interactions between sectors of human activity
    + Stepwise process: adaptive & flexible, responsive to monitoring/research results
    + Inclusive/collaborative: participation from all levels of government/indigenous peoples/stakeholders encouraged/balances diverse/interconnected needs of society + environment

<br>
<br>


### Debrief

Go over your notes & briefly answer these questions:

*	What was the most muddy concept(s)? Do we need to further clarify?
*	What was the exciting, interesting, or a new concept you learned?
*	Was there any “assumed background knowledge” you didn’t have? Do we need to further clarify?
*	Any additional general comments or questions on today's lecture or this week’s lab?

Submit your answers [`r icon::fa("clipboard-list")`](https://docs.google.com/forms/d/e/1FAIpQLSf_wpIenOLXtsZ24-3Aa120mgZmN3ioZHVkA342ZCYOj5OQug/viewform?usp=sf_link).


<br>

**Due by 3pm the day after lecture.**


### Dig a little deeper

Additional resources:

`r icon::fa("book-reader")` 



### Review

* Compare and contrast the focus of conserving individuals species and complete ecosystems. Determine whether these are mutually exclusive and if now what those areas of overlap look like.
* Give two arguments why focusing solely on ecosystems for conservation might actually be disadvantageous for individual populations of endangered species.
* Give a brief definition of a protected area.
* The IUCN has seven categories for protected areas. Give a brief (1-2 sentence) description of their central goals, then compare and contrast them in terms of their purpose, focus, and objectives.
* Give a brief description of of the positive impacts of protected areas on the human well-being of individuals and their local communities (consider economic, social, political, and wellness aspects).
* Social pressure from affected local communities has led to downgrading, downsizing, and degazettement (loss of protected status) for some protected areas. Explain what the downsides of protected areas are that have caused this and determine what measures could be taken to reduce the negative impacts.
* List six frameworks used to prioritize areas for conservation; for each give a brief description of the criterion being applied and a brief statement of the central limitations to this approach from a conservation perspective.
* Overall, terrestrial and marine protected areas have been shown to have increased habitat cover, better habitat quality compared to areas outside the PA or matched areas resulting in a higher species richness and larger population sizes. However, on an individual level not all protected areas are successful.
    + List the three most common threats to PAs
    + Give a brief description of two of the most effective predictors of the success of a PA.
* Recent evidence has shown that conservation efforts can be just as effective in sustainable use protected areas compared to traditional strict PAs. Explain the importance of focusing on social development and conservation goals in the planning of PAs and how this may increase the success of the PA overall, despite this frequently resulting in less strict regulations of PAs.
* Habitat loss, fragmentation & degradation has resulted in landscape mosaics. Briefly describe three arguments outlining the need for landscape-level conservation.
* When establishing new protected areas the focus can either be to maximize biodiversity conservation through individual protected areas or across a landscape using a network of protected areas. Briefly compare and contrast desirable properties for design when focused on individual PAs vs networks.
* Briefly describe three arguments supporting the importance of connectivity of PAs as a key requirement to increase their effectiveness and ensure persistence of population being protected. Briefly describe two commonly used methods to connect PAs in networks.
* Give a brief explanation of why it is important for unprotected areas to be managed and accounted for in conservation efforts at a landscape-levels.
* The land-use continuum classifies habitats by their **patterns** ranging from artificial to natural (e.g. housing, road density, proportion of natural vegetation cover) and **processes** ranging from controlled to free (e.g. historic range of variability, dam density). Argue where you think industrial/urban habitat, city parks, wilderness, traditional agriculture, suburbs, and national parks fall on this continuum and whether the extent to which they can be managed to serve as viable habitat for species.
* Tropical forests, privately owned land, urban settings, and land used for agriculture are habitats/large tracts of land that are frequently unprotected. For each, give a brief description of how these habitats can still be incorporated into management plans for species even though they do not constitute protected areas using an example.
* Agriculture occurs on a spectrum of how sustainable farming practices are. Briefly compare and contrast conventional farming, sustainable intensified framing and organic/agroecological farming to argue which provides the most options to maintain biodiversity levels and be integrated into landscape-scale conservation (useful categories include use of fertilizer/pesticides, crop/livestock diversity, spatial heterogeneity, non-farmed biodiversity, provision/use of ecosystems).
* Use an example to explain why agro-ecological farming allows for better integration into landscape-scale conservation/management plans.
* Give a brief description of multiuse/mixed-use habitats and compare & contrast them to protected areas, in terms of purpose and use.
* Give two arguments of why despite protecting biodiversity increaslngly being incorporated as an explicit goal of land management incoporating mixed-use habitats in landscape-level conservation plans can still be difficult.
* Give a brief description of ecosystem-based management, including key goals and characteristics. Argue why you think it has become the standard especially for fisheries management.


<br>

Download a hard copy of the recap questions [`r icon::fa("file-download")`](files/BI328_ReviewQs_SpeciesConservation.pdf).
