---
title: "Conservation Biology (BI328)"
description: | 
  Fall 2020 Lectures
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

```

# Introduction to Conservation Biology

### Outline

**Goals of Conservation Biology**

* Investigate & describe biodiversity (variety of life)
* Evaluate/predict effects of human activities on biodiversity.
* Develop practical solutions to protect/manage biodiversity in a sustainable way


**Different Viewpoints of Conservation Biology**

* Preservation
* Resource Management
* Applied Ecology


**The interdisciplinary nature of Conservation Biology**

* "founded" to combine practical experience of wildlife biology, ecology, forestry, fisheries, and national parks management & theory of biological sciences (population biology, biogeography, ecology, zoology, botany).
* draws from disciplines in physical, social, and implementational environment


**Comparison to Environmental Science & Environmentalism**

* Environmental Science comprises five fields: Social Sciences, Geosciences, Environmental Chemistry, Ecology, Atmospheric Science
* Ecology focus on interactions of organisms with the biotic and abiotic components
* Conservation Biology focus on impact on biodiversity
* Environmentalism focuses on philosophical/ethical arguments & the intrinsic value of nature

**Crisis Discipline**

* Managers required to make best decision possible even with incomplete data.
* Conservation biologist are called up to provide quick, unambiguous answers with incomplete data.


**Two-sides of a coin**

* Subjective/value-based discipline (science as guide to conservation/management)
* Objective/evidence-based discipline (science central role to understand systems and quantify trade-offs)
* Evolution of Core Principles & Values


### Assigned readings

**Reading reflections due: n/a**

`r icon::fa("book-reader")` Cardinale et al. 2019. **Conservation Biology**. Chapter 2


### Debrief

Go over your notes & briefly answer these questions:

*	What was the most muddy concept(s)? Do we need to further clarify?
*	What was the exciting, interesting, or a new concept you learned?
*	Was there any “assumed background knowledge” you didn’t have? Do we need to further clarify?
*	Any additional general comments or questions on today's lecture or this week’s lab?

Submit your answers [`r icon::fa("clipboard-list")`](https://docs.google.com/forms/d/e/1FAIpQLSf_wpIenOLXtsZ24-3Aa120mgZmN3ioZHVkA342ZCYOj5OQug/viewform?usp=sf_link).


<br>

**Due by 3pm tomorrow.**


### Dig a little deeper

Additional resources:

`r icon::fa("book-reader")` Callicott. 1990. Wither Conservation Ethics

`r icon::fa("book-reader")` Soule. 1985. What is Conservation Biology?

`r icon::fa("book-reader")` Kareiva and Marvier. 2012. What is Conservation Biology?



### Review

* List the central goals of Conservation Biology.
* Explain how Conservation Biology differs from other biological sciences (genetics, physiology, ecology, ...).
* Compare and contrast concepts of conservation as preservation, resource management, and as a sub-discipline of ecology/evolution.
* Compare and contrast Conservation Biology, Environmental Science, and Environmentalism.
* Compare and contrast the two viewpoints of Conservation Biology as a subjective/value-based discipline and objective/evidence-based discipline.


<br>

Download a hard copy of the recap questions [`r icon::fa("file-download")`](/files/BI328_ReviewQs_Intro_Conserv_Bio.pdf).
