---
title: "Conservation Biology (BI328)"
description: | 
  Fall 2020 Lectures
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

```

# The Biodiversity Crisis


### Assigned readings

**Reading reflections due: Sept 18th, 5pm**

`r icon::fa("book-reader")` Cardinale et al. 2019. **Conservation Biology**. Chapter 8

`r icon::fa("book-reader")` Cardinale et al. 2019. **Conservation Biology**. Chapter 9

*Food for thought*

Is the current focus on a potential 6th mass extinction an overreaction?

We extensively discussed biodiversity and how it can be described at different hierarchical scales (genetic, species, ecosystem) and using different frameworks (compositional, structural, functional) and yet we are using extinction (complete loss at species level as our only measure) - do you think this is a good proxy?

Is pollution a type of habitat degradation or is habitat degradation one (of many) effects of pollution?


<br>
<br>

**Reading reflections due: Sept 25th, 5pm**

`r icon::fa("book-reader")` Diaz, R. J., & Rosenberg, R. (2008). Spreading dead zones and consequences for marine ecosystems. science, 321(5891), 926-929.

`r icon::fa("book-reader")` Cardinale et al. 2019. **Conservation Biology**. Chapter 10

*Food for thought*

Before reading more about eutrophication, had you considered "nitrogen" a pollutant?

Consider how the formation of dead zones as a consequence of eutrophication might play with climate change, another important driver of biodiversity loss.

Consider how overexploitation differs from other drivers of biodiversity loss as we are directly causing increased mortality.

Consider how overexploitation has many stakeholders - how does this complicate mitigation?


<br>
<br>

**Reading reflections due: Oct 2nd, 5pm**

`r icon::fa("book-reader")` Cardinale et al. 2019. **Conservation Biology**. Chapter 11

`r icon::fa("book-reader")` Cardinale et al. 2019. **Conservation Biology**. Chapter 12

*Food for thought*

Consider the difference in mechanisms of invasive species entering a novel habitat on their own e.g. through range expansion compared to humans intentionally introducing a species to an ecosystem.

Consider if we should differentiate between invasive species that are "beneficial" vs "harmful" to an ecosystem.

Consider how human indirectly cause invasions through climate change compared to direction by intentionally and unintentionally circumventing dispersal limitations.

Consider difference between climate change directly causing species to go extinct by altering abiotic conditons compared to biotic factors like shifting species assemblages, altering the timing of organisms being present in ecosystems, altering species distributions, altering relative abundances of species. Which do you think is the greater problem?

Consider whether we should be putting more emphasize on ensuring climate refugia for worst case scenarios or preserving biodiversity in current hotspots.


<br>
<br>


**Reading reflections due: Oct 9th, 5pm**

`r icon::fa("book-reader")` Executive summary (p. 7 - 10) of [Leadley, P. (2010). Biodiversity scenarios: projections of 21st century change in biodiversity, and associated ecosystem services: a technical report for the global biodiversity outlook 3 (No. 50). UNEP/Earthprint.](https://www.cbd.int/doc/publications/cbd-ts-50-en.pdf)

*Food for thought*

Consider how synergistic effects of different drivers acting on the same system may contribute to tipping points.

Consider whether we should focus on entire ecosystems remaining intact compared to preserving individual species.


<br>
<br>




### Debrief

After each lecture go over your notes & briefly answer these questions:

*	What was the most muddy concept(s)? Do we need to further clarify?
*	What was the exciting, interesting, or a new concept you learned?
*	Was there any “assumed background knowledge” you didn’t have? Do we need to further clarify?
*	Any additional general comments or questions on today's lecture or this week’s lab?

Submit your answers [`r icon::fa("clipboard-list")`](https://docs.google.com/forms/d/e/1FAIpQLSf_wpIenOLXtsZ24-3Aa120mgZmN3ioZHVkA342ZCYOj5OQug/viewform?usp=sf_link).

<br>

**Due by 3pm the day after lecture.**

### Outline: The Biodiversity Crisis

**Global Patterns of Biodiversity loss**

* State of Biodiversity
    + state of biodiversity declining trend
    + pressures of biodiversity increasing trend
    + responses to address loss increasing trend
* Understanding patterns of biodiversity loss
    + "levels" of extinction
    + tracking (future) loss through IUCN Red List
    + Global change in species diversity is a result of extinction & speciation
    + determining if contemporary accelerated loss of species diversity is a mass extinction requires determining the rate of extinction and the proportion of existing species being lost
    
**Drivers of Extinction**

* understanding drivers of extinction/biodiversity loss meanse we must address the ultimate causes of loss
    + increasing numbers of humans
    + increasing exploitation of natural resources
    + addressing the causes not the symptoms means implementing sustainable use of resources
* Drivers of the loss of biodiversity
    + Habitat loss/fragmentation
    + Pollution
    + Invasive species
    + Overexploitation
    + Climate change
* Multiple interacting threats can lead to synergistic effects
    + some taxonomic groups more affected than others
    + some habitats more affected than others
    
**Local & Regional Patterns of Biodiversity Loss**

* local changes in species diversity are result of local extirpation and migration/colonization
* expected number of extinctions due to habitat loss can be modeled using species/area relationships
    + expected/observed patterns are not always accurate
    + extinction debt
    + oversimplified assumptions
* biodiversity can be monitored using spatial and temporal comparisons
    + patterns of local changes in species diversity are not just net loss due to complex interactions
    + Experimental design is challenging & can be limiting to interpret results
    + Lack of clear baselines
    + Complete loss of species may not be adequate measure of impact
    + our assumptions of mechanisms are likely too simple

**Intrinsic Vulnerability of species**

* Some species are more vulnerable to extinction
    + high habitat specificity
    + limited geographic range
    + life-history parameters
    + demographics
    
* Stochastic effects make small populations more vulnerable
    + demographic stochasticity
    + environmental stochasticity
    
* Demographics
    + Population size
    + population growth rate
    + population density
    
* Habitat, range & connectivity
    + geographic range & habitat
    + connectivity and isolation
    
* Life history traits (triangular life history model)
    + lifespan, juvenile survivorship, adult mortality
    + age-at-maturity, fecundity
    + body size, growth
    
**Habitat Loss**

* Definition(s) of habitat loss
    + Habitat loss (destruction)
    + Habitat fragmentation
    + Habitat degradation
    
* Habitat loss resulting from land-use change is most significant driver of biodiversity loss

* Primary drivers of habitat loss
    + Agricultural expansion
    + Urbanization
    + Extractive Industries
    
* Effects of increasing land-use intensity on biodiversity
    + differential impacts on taxonomic groups
    + differential impacts on biomes
    + intensity of land-use & type of human-dominated ecosystem determines impact
    
**Habitat Fragmentation**

* Habitat fragmentation is more than habitat loss
    + reduction of habitats to size too small to support some species (may need large territory) 
    + Creation of large amounts of degraded “edge” habitat
    + may force species into a metapopulation structure (more vulnerable to stochastic effects)

* Habitat patch configuration determines impact
    + size of habitat patches
    + number of habitat patches
    + distance/isolation among habitat patches
    + area:perimeter ratio of patches (edge habitat)

* Patch size & number
    + Decrease in patch size results in decrease of original habitat remaining (species-area relationship)
    + Extinction thresholds: Threshold of habitat size required for species persistence
    + number of patches often highest at intermediate levels of habitat loss
    + Patches in a landscape can be sufficiently heterogeneous to increase diversity across landscape by adding new species (create new niches)
    
* Edge habitat/Edge effects
    + edge habitats (ecotones) mark the transition between two different habitats
    + increased fragmentation means landscapes consist of increasing number of small patches
    + Proportion of edge habitat increases as patch gets small
    + Proportion of interior (core) habitat decrease with patch size 
    + Perimter:Area ratio increases as patch size decreases
    + Edge Effects are physical & biological changes occurring at patch edges (example forest canopy stabilizes microclimate)
    + Edge habitats have winners
* Patch isolation
    + Isolation is function of distance between habitat patches & the matrix that separates them
    + Barriers to dispersal (roads, railway, fences, water channels) may also result in fragmentation
    + organisms with ontogenetic shifts and isolated/small populations at greater risks
    + may force species into meta-population structure
    
    
**Metapopulations**

* Patchy landscape may force meta-population structures
    + habitats lost/converted to human use and/or heavily degraded
    + Intact patches are small, fragmented & disconnected
    + Small, isolated populations in single habitat patch are highly vulnerable to extinction
    + Species may persist as a whole if patches are connected by occasional movement (dispersal/migration resulting in gene flow)
    
* Metapopulation structures
    + Definition: Collection of local populations spatially separated (individual habitat patches) connected by dispersal
    + Landscape has habitat patches that are suitable but unoccupied
    + Individuals in small, localized populations have limited lifetime (local extinctions
    + Suitable habitats are (re)colonized
    + Metapopulation as a whole persists if rate of colonization > rate of extinction
    
* Source-sink dynamics
    + Habitat patches vary in quality & size 
    + some populations (sinks) relying on constant input of immigrants from populations in high quality habitat patches (sources)
    
* Metapopulation theory applied to conservation
    + predict extinction risk
    determine patch size & connectivity thresholds to restore habitat/ensure long-term persistence


**Habitat Degradation**

* Habitat degradation is the result of human activities decreasing habitat quality resulting in the erosion of biodiversity
    + primary causes are desertification, soil erosion & sedimentation
    + habitat degradation can be caused by habitat fragmentation (edge effects)
    + pollution may also result in habitat degradation in the broadest sense

* Sediment erosion occurs when soil particles become detached by water, wind, or gravity and are transported away from their original location
    + main causes are overgrazing, deforestation, unsustainable agriculture resulting in the loss of primary vegetation which mitigate soil erosion through their roots which stabilize the top soil and retain moisture

* Soil erosion and sedimentation affect biodiversity & human well-being
    + Increased turbidity loss of sunlight for plants/visibility for animals)
    + Decrease available oxygen
    + Problematic for filter feeders
    + Affect drinking water (increased water treatment costs)
    + Increased flooding, clogged storm water pipes/storage systems
    + Property damage/value reduction
    
* Desertification is the result of poor soil management leading to soil degradation causing dry lands to become increasingly arid, loss of water bodies, vegetation & wildlife
    + ultimate cause: increasing heat waves/drought + increasing population size
    + e.g overgrazing results in shrub establishment & grassland degeneration, increased spatial heterogeneity, and soil compaction (desertification) compounded by wind erosion, nutrient loss, and water runoff
    + climate change contributes to accelerate the process
    + Soil erosion, desertification, climate change, biodiversity loss are linked in positive feedback loop accelerating the processes
    
**Pollution**
    
* Pollution directly and indirectly impacts species
    + industrial pollutants (toxic metals, acid rain, ...
    + Pharmaceutical pollutants & personal care products
    + Pesticides & Herbicides
    + Nutrients
    + Oil spills
    + Plastics
    
* Many pollutants are persistent and stay in organisms/environment for a long time/able to harm long after & great distance from initial release
    + Point source contamination: trace to specific points of discharge from waste water, treatment plants, factories, combined sewers
    + Non-point sources result from run-off transporting pollutants into aquatic systems
    + Air pollution spreads across the landscape, often overlooked as non-point source of pollution, may travel far
    + Eroded soil & sediment can transport considerable amounts of nutrients (e.g. organic nitrogen, phosphorous, pesticides to rivers, streams)
    
* Pesidiced impact wildlife   
    + decrease wild plants & birds
    + reduce biodiversity of stream inverts
    
* Biomagnification of results in DDT, organochlorine pesticides, organic metals, and other toxic chemical compounds becoming concentrated at higher trophic levels of the food chain

* Heavy (toxic) metals (lead, zinc, mercury, cobalt) released into environment through mining, smelting, leaded gasoline, coal burning, electronic waste
  + direct effects (Lethal effects): toxic metal poisoning
  + indirect effects (sublethal effects): Increasing susceptibility to disease, decreased fecundity, …

* Effects of Pharmaceuticals & Personal Care Products on biodiversity are poorly understood - but it's not good
    + enter environment through hospitals, households, industries discharge directly surface waters and Excretion, improper disposal of medicines into plumbing (indirectly)
    + PPCPs are ubiquitous in the environment
    + Wastewater treatment facilities do not have technology to get out of systems
    + Example: Feminization of male fathead minnows: Exposure to 17-ethynylestradiol feminizes the male fathead minnow, reduce size of their gonads, loss of males lead to reproductive failure
    
* Nutrient overload leads to eutrophication and dead zones
    + Macronutrients: Carbon, Nitrogen, Phosphorus
    + Phosphorus is limiting nutrient freshwater systems/nitrogen in marine systems
    + Algal blooms occur when there is sufficient sunlight, nutrients, and optimum temperature - once consumers (zooplankton) increase & nutrients are used up they subside
    + Nutrients/organic matter from sewage treatment plants, effluents, Stream input, local non-point drainage, and direct rainfall result in eutrophication
    + Eutrophication fuels high rates of phytoplankton growth and biomass accumulation
    + Phytoplankton die and are decomposed using up the oxygen resulting in hypoxia/anoxia (dead zones)
    + Fish either flee low-oxygen regions or die
    
* Plastics have strong & varied impact on biodiversity
    + especially in marine systems plastics are growing form of environmental pollution
    + effects are ingestion, entanglement, organic pollutants/metals, microplastics
    + microplastics are an emergent contaminant with wide range of sources and potential for bioaccumulation of toxic plastic additives and organic pollutants (e.g DDT and PCB) that adsorb to microplastics
    + filter feeding marine megafauna especially prone to microplastic ingestion (bioaccumulation may result)
    
* Oil spills
    + sources include tankers (reduced w/better navigation resulting in less accidents), pipelines (3-fold increase since 1970), oil storage/refineries (5-fold increase since 1970), and exploration/production facilities (2010 DWH oil spill largest marine oil spill with 134 - 206 mill gallons).
    + oil spills impact biodiversity directly through exposure to oil, and indirectly when chemical dispersants used to break down oil themselves are toxic.
    + Exxon Valdez tanker spill in 1989 (Prince William Sound) has had lasting impacts with oil still persisting in some beach locations and some species & ecosystems have still not recovered.
    + The Deepwater Horizon oil spill leaked 19x more oil than Exxon Valdez, only 25% of oil was recovered (deepwater blowout); the use of dispersents had negative impacts (e.g. on corals), direct exposure to oil has multiple pathways resulting in lethal and sublethal effects. Much of the oil ended up on the seafloor with lasting impacts.


**Overexploitation**

* Overexploitation (Overharvesting) is the harvesting of a renewable source faster than it can be produced
    + wild plants/animals
    + whole ecosystems
    + resources required to sustain life
    
* Persistent overexploitation may lead to complete destruction of a resource
    + Overexploitation is not a new phenomena
    + impact on biodiversity is increasing in anthropocene as human populations are larger & technology has improved
    
* Humans rely on domestic & wild organisms as food sources
    + 62 developing countries rely on wildlife for at least 1/5 of their animal protein (insects, amphibians, reptiles, birds, fish, rodents, larger mammals)
    + Fish provides 3 billion people with almost 20% of their average animal protein intake
    
* Exploitation of a common pool resource may lead to tragedy of the commons: Collective action of many individuals pursuing own self interest depletes, spoils, destroys the resource to the detriment of everyone

* Types of exploitation
    + Commercial exploitation
    + Subsistence exploitation
    + Recreational exploitation
    
* Subsistence exploitation is having an increasing impact
    + Growing problem in developing countries faced with food insecurity
    + with better access, technology & market for wild meat
    + Increase of poaching pressure inside parks leads to conflict
    + bushmeat can result in transmission of zoonotic disease

* Recreational overexploitation   
    + hunting & fishing
    + recreational past time & cultural significance 
    + most targeted animals not threatened
    + impact differs by animals being hunted (trophy hunting vs. population control)
    + many hunters are proponents of conservation efforts
    + discussion on the up/downside of trophy hunting
    
* Commercial exploitation
    + legal/illegal wildlife trade
    + fish
    + logging

**Overfishing**

* recreational fishing contributes to overfishing (may exceed commercial landings for some species)

* global paterns of overfishing & regulation
    + approx. 33% fished at unsustainable rate, 60% maximal sustainable rate, 7% underfished
    + Areas w/poor regulation/enforcement vs areas that are well regulated/managed

* uncheck fishing pressure may lead to collapse of fishery
    + Atlantic Cod: mismanagement
    + Peruvian Anchovata: regime shifts (El Nino)
    + Atlantic herring: technology
    + other contributors: open access resource, population expansion, conflicts between fisheries, subsidies
    
* does overfishing lead to extinction?
    + well-documented link in terrestrial species between overharvesting + extinction
    + few verifiable extinctions in the ocean, though cases of local extirpations & becoming functionally extinct do exist
    + many exploited fish have high rebound potential
    
* Fisheries crisis
    + state of fisheries varies: 35% in decline, 25% in recovery, 37% healthy/sustainably fished
    + overfishing + habitat destruction leads to population collapse
    + fishing impacts more than just the target species (bycatch, physical impact of gear, new ecosystems/habitats, fishing down the food web)
    
* Sustainable fishing
    + regulatory measures include restrictions on time, space, size & gear
    + Catch share programs allocate area or privilege to harvest share of total catch to establish controls on fishing pressure
    + quotas are determined based on the fundamental principle of maximum sustainable yield (point at which population can reproduce indefinitely despite harvesting pressure); models include fixed quotas and fixed effort
    + Criticism of MSY includes oversimplification of the model and its assumptions, lack of information on species can lead to quotas being set unsustainably, difficult to account for stochastic effects
    + MSY no longer considered an appropriate upper limit (should not be the target) though more sophisticated models are built on same principle


**Invasive species**

* Global patterns of invasive species

* Definitions
    + Native/indigenous species: occurs w/in its past or present natural range
    + Introduced species: Intentionally or unintentionally introduced to location outside its past or present natural range (beyond its natural dispersal abilities)
    + Invasive species: Non-native species established in natural/semi-natural ecosystem/habitat; is an agent of change/threat to native biodiversity
    
* Increasing rate of invasive and introduced species assisted by humans
    + Dispersal limitation is the greatest barrier to range expansion
    + human serve as transport vectors (intentional + unintentional)


* Biological interactions influence establishment
    + Establishment in new habitat/ecosystem is not guaranteed
    + Spread and proliferation of invasive species has distinct phases
    
* Invasive species negatively impact biodiversity
    + can cause extinctions (predation, competition)
    + may increase biodiversity when pace of invasion > pace of extinctions
    + invasive species impact biodiversity: predation, competition, hybridization, homogenization, as pathogens or importing pathogens
    + invasive species may reduce biodiversity as predators and competitors (lionfish)
    + cause biotic homogenization
    + may alter ecosystem functioning and habitats as a whole
    + can have significant negative impact on economy

* Invasive species can have intended positive impact
    + intentional introductions for agriculture & as food source 
    + rebuild forests
    + biological pest controls
    
* Management & Control
    + effective measures depend on stage of species' establishment - early intervention is important
    + some measures are controversial (use of poison, trappings)
    + characteristics of successful eradication programs

**Climate Change**

* Human activities are effecting global, simultaneous change of abiotic parameters (climate change)
    + components of climate change (abiotic factors affected)
    + levels of biological response
    
* Persistence in an altered climatic niche
    + changing climate alter condition in the native habitat
    + to persist species must have ability to adapt or migrate
    + responses to allow species to persist: change in local phenotype, phenology, spatial distributions
    
* Modeling climate change to predict responses
    + Identify spatial, demographic & life history characteristics that are important predictors of risk
    + past trends are not good predictors
    + different climate scenarios are used to determine different levels of impact
    
* Documented responses to climate change
    + population decay/ local extirpation
    + geographic range shifts
    + altered phenologies
    + biome regime shifts/alternative states
    
* Change in ecosystem services impact human well-being
    + diseas outbreaks/spread
    + provisioning services (raw materials, food sources)
    + pollinator services
    + range shift in fisheries may create new services
    
* Managing effects of climate change on biodiversity
    + establish refugia & safe havens
    + optimize migration pathways
    + build evolutionary resilience/conserve adaptive potential
    
* Using biodiversity to manage/mitigate effects of climate change
    + use biodiversity for climate mitigation (e.g. carbon sequestration)
    + develop green infrastructure: use regulating ecosystem services to mitigate impact of floods, natural disasters


**Tipping Points, Resilience & Persistence**






### Dig a little deeper

Winemiller (2005) Life history strategies, population regulation, and implications for fisheries management." Canadian Journal of Fisheries and Aquatic Sciences 62.4: 872-885.

Kindsvater et al. (2016) Ten principles from evolutionary ecology essential for effective marine conservation. Ecology and Evolution 6.7: 2125-2138.

Newbold et al. (2015) Global effects of land use on local terrestrial biodiversity. Nature 520.7545 (2015): 45-50.

Geiger et al. (2010) Persistent negative effects of pesticides on biodiversity and biological control potential on European farmland. Basic and Applied Ecology,11(2), 97-105.

Beketov et al. (2013) Pesticides reduce regional biodiversity of stream invertebrates. Proceedings of the National Academy of Sciences, 110(27), 11039-11043.

Kidd et al. (2007) Collapse of a fish population after exposure to a synthetic estrogen. Proceedings of the National Academy of Sciences, 104(21), 8897-8901.

Vaquer-Sunyer & Duarte (2008) Thresholds of hypoxia for marine biodiversity. Proceedings of the National Academy of Sciences, 105(40), 15452-15457.

Rabalais & Turner (2019) Gulf of Mexico hypoxia: Past, present, and future. Limnology and Oceanography Bulletin, 28(4), 117-124.

Germanov et al. (2018) Microplastics: no small problem for filter-feeding megafauna. Trends in ecology & evolution, 33(4), 227-232.

Lee et al. (2013) Lab tests on the biodegradation of chemically dispersed oil should consider the rapid dilution that occurs at sea. Marine pollution bulletin, 73(1), 314-318.

Pulster et al. (2020) A first comprehensive Baseline of Hydrocarbon pollution in Gulf of Mexico fishes. Scientific reports, 10(1), 1-14.

Schwing et al. (2015) A decline in benthic foraminifera following the Deepwater Horizon event in the northeastern Gulf of Mexico. PLoS One, 10(3), e0120565.

Schreiber & Halliday (2013) Uncommon among the commons? Disentangling the sustainability of the Peruvian anchovy fishery. Ecology and Society, 18(2).

Lluch-Cota (2013) Modeling sardine and anchovy low-frequency variability. Proceedings of the National Academy of Sciences, 110(33), 13240-13241.

Hickling et al. (2005) A northward shift of range margins in British Odonata. Global Change Biology 11.3: 502-506.

Morellato et al. (2016) Linking plant phenology to conservation biology. Biological Conservation 195: 60-72.

Sgrò et al. (2011) Building evolutionary resilience for conserving biodiversity under climate change. Evolutionary applications, 4(2), 326-337.

Leadley, P. (2010) Biodiversity scenarios: projections of 21st century change in biodiversity, and associated ecosystem services: a technical report for the global biodiversity outlook 3 (No. 50). UNEP/Earthprint.



<br>

### Review

1. Define what a species extinction and its consequences are.

2. Describe the difference between a species being globally extinct, extinct in the wild, extirpated, and functionally extinct. 

3. List the two mechanisms resulting in global change in species diversity. Contrast these with the two mechanisms resulting in local/regional change in species diversity.

4. Define what a mass extinction event and what the background extinction rate are.

5. Give a testable hypothesis for a mass extinction rate and use that to argue whether or not we are currently experiencing the "6th mass extinction".

6. Give a brief description of the current accelerated loss of biodiversity and contrast that to the five mass extinctions our planet experienced in geological history.

7. List the five major categories of drivers of biodiversity loss. Contrast them in terms of their contributions to biodiversity loss across broad categories of vertebrates and habitats.

8. Compare and contrast spatial and temporal designs to monitor biodiversity. Argue which one you think is more informative.

9. Compare and contrast the observed global pattern of biodiversity loss with the local/regional change in species diversity.

10. Define what intrinsic vulnerability is and list the four major factors that contribute to the intrinsic vulnerability of a species.

11. Compare and contrast demographic and environmental stochasticity and explain how they can contribute to species extinction.

12. Population size, density and growth rates are important parameters determining the demographics of a population. For each briefly assess how they can increase vulnerability to extinction.

13. Habitat, range, and connectivity among populations are important ecological characteristics that may contribute to the likelihood of a species going extinct. Explain.

14. Argue whether having migration and/or a dispersal stage as part of the life history of a species increase or decreases the extinction risk of a species?

15. The triangular life history model groups individuals into opportunistic, periodic, and equilibrium species based on the optimization of three demographic parameters, generation time, juvenile survivorship, and fecundity. Opportunistic species are characterized by short generation times, low juvenile survivorship, and low fecundity. Equilibrium species are characterized by high juvenile survivorship, long generation times, and low juvenile survivorship. Finally, periodic species are characterized by high fecundity, low juvenile survivorship, and long generation times. Argue how you would rank these life history strategies by level intrinsic vulnerability of the species.

16. List important life history parameters to consider when assessing the intrinsic vulnerability of a species, indicate how they increase/decrease intrinsic vulnerability. You can create a table where you list the parameter and then use arrows to indicate if intrinsic vulnerability increases/decreases as that parameter increases/decreases.

e.g.

parameter        | intrinsic vulnerability |
-----------------| ----------------------- |
age-at-maturity ↑|  ↑                      |


17. a Elephants generally have small population and their life history is characterized by a late-age-at maturity, high parental care, and long generation time. By contrast, squirrels are abundant throughout their wide geographic range. Their life history is characterized by a short generation time, and high fecundity. Argue which species has the higher intrinsic vulnerability. 

17. b Plot twist: The British red squirrel has a geographic range extending from Siberia to Ireland and despite its overall abundance decreasing it is categorized as a species of least concern by the IUCN. Since the introduction of gray squirrels from North America this invasive species frequently outcompetes native red squirrels and (ironically) transmits a squirrelpox virus lethal to native red squirrels which are now only found in a few small population in southern Scotland. Argue whether you think the British red squirrel is correctly categorized by the IUCN.

18. Define habitat loss/destruction, habitat fragmentation, and habitat degradation.

19. List the main drivers of habitat loss.

20. Briefly describe how land-use change results in habitat loss and describe how variation in the land-use intensity may have differential impacts on the biodiversity.

21. Compare and contrast habitat loss and habitat fragmentation in terms of their impact on biodiversity.

22. Briefly describe the main effects of habitat fragmentation on biodiversity.

23. List the four parameters used to describe habitat patch configuration and briefly describe their relationship to habitat loss (you may sketch a figure but make sure to label axis).

24. Briefly explain how habitat patch size and number affect biodiversity (remember "explain" means you need to describe the effect + give a "why").

25. Briefly describe the term Extinction Threshold.

26. Describe the relationship of edge habitat, loss of biodiversity and patch size & number.

27. Define what edge effects are and use an example to explain how they result in additional degradation of the remaining habitat patches.

28. List the three main groups of species that may benefit from edge effects; describe one of the parameters using an example.

29. The isolation of of habitat patches is a function of the geographic distance between them and the parameters of the matrix separating them. Explain.

30. Briefly describe three ways that patch isolation and barriers negatively affect organisms potentially increasing their extinction risk.

31. Give a brief description of what a metapopulation using a brief definition and listing key characteristics. 

32. Explain how habitat fragmentation forcing species into a meta-population structure can increase extinction risk as a whole

32. Metapopulations are characterized by source-sink dynamics. Explain what this means and argue how this effect can allow a population affected by habitat fragmentation to persist despite local extirpations.

33. Give a brief description of how metapopulation theory can be applied to conservation.

34. Habitat fragmentation has resulted in species A being restricted to a series of small, highly isolated habitat patches. By contrast, species B has several suitable habitat patches available that are connected by dispersal, though in some locations there have been local extirpations due to stochastic effects. In both cases, the local populations are small and some habitats have been further degraded by pollution. Compare and contrast these two species and their local populations in terms of their extinction risk.

35. Define habitat degradation, list the major causes and explain how habitat loss and fragmentation may each contribute to habitat degradation.

36. Briefly describe the causes, process, and effects of soil erosion & sedimentation on biodiversity & human well-being.

37. A patch of tropic rain forest can be valued for its direct value as provisioning ecosystem service or its indirect value as a regulating ecosystem service. Describe its value in the context of habitat degradation to argue whether you think higher value should be placed on the provision ecosystem or regulating ecosystem service.

38. Briefly explain the process of desertification using an example (be sure to describe causes & effects).

39. Desertification, biodiversity loss, and climate change are linked through multiple positive feedback loops. Explain what a positive feedback loop is using one of these inter-connected mechanisms as an example (use an example if that is helpful for you).

40. List six major categories of pollutants.

41. Compare and contrast pollution and habitat degradation.

42. Compare and contrast point and non-point sources of pollutants using specific examples for each and argue which group of sources you think has a greater impact on ecosystems.

43. Use an example to explain the process of biomagnification.

44. Use toxic metals as an example to explain the difference of sublethal and lethal effects of pollution.

45. List a range examples of pharmaceutical and personal care products and explain how they enter the environment.

46. Describe what a bioindicator is using aquatic invertebrates as an example.

47. Explain what nutrient run-off is, explain how it leads to eutrophication and so-called dead zones, list ecosystems typically affected by dead zones, and describe how it impacts biodiversity (give two specific examples of affected taxonomic groups).

48. List the four main ways plastics impact biodiversity (especially in marine systems).

49. Describe what microplastics are, their sources/how they enter the environment and outline two major ways they can impact organisms. 

50. List the four main causes of oil spills.

51. List direct and indirect impacts of oil spills on biodiversity, use examples of which type of organisms and/or ecosystems may be affected.

52. Argue why you think some species may recover more quickly from an oil spill like Exxon Valdez than others.

53. Briefly describe what dispersants are and how they are used to mitigate oil spills and use an example to explain how they may do more harm than good.

54. Explain the difference between lethal and sublethal effects and argue which you think will have the greater impact on biodiversity (consider long vs. short-term impacts).

55. Give a brief definition of overexploitation and list the different groups of resources that may be affected.

56. Argue why overexploitation is the second largest driver of biodiversity loss after habitat loss/destruction.

57. Define what a common-pool resource is and list three examples. Use one of these examples to explain the concept of the tragedy of the commons.

58. List 5 reasons for overexploitation.

59. Briefly define the three types of overexploitation.

60. Define what subsistence overexploitation is and briefly outline why it is having an increasing impact on biodiversity.

61. Define what recreational exploitation is and list the two major categories.

62. Contrast two widely-held but opposing opinions that recreational hunting is beneficial for biodiversity and conservation efforts versus recreational hunting being harmful to species being hunted.

63. Argue whether trophy hunting harms or benefits local biodiversity and local economies (remember argue means you should list arguments on both side and come to a conclusion based on those).

64. List the three major categories of commercial exploitation.

65. Compare and contrast recreational and commercial fisheries (consider points such as impact, locations/affected ecosystems, habitats, targeted species/fish within a population).

66. Briefly describe the current status of global patterns of overfishing.

67. Fishing pressure (unsustainable yields) may lead to a fisheries collapse. List three other factors that frequently co-contribute. Use an example to describe one mechanism in detail.

68. Briefly explain why there is a well-documented link between overharvesting and extinction in terrestrial species while there are only few verifiable extinctions of marine fish due to overexploitation (i.e. explain why exploited marine fishes may be less or terrestrial species more vulnerable).

69. List four ways fishing impacts more than just the target species. Briefly describe two of these mechanism in more detail.

70. Briefly describe the four main regulatory measures that can be used to regulate a fishery.

71. Explain the difference between an quota-based versus an area-based catch share program (remember this includes defining what each of these is).

72. Briefly define what the maximum sustainable yield is and how it can be used to limit overexploitation. Briefly outline problems with the concept of MSY.

73. Compare and contrast the concepts of a native (indigenous species), an introduced species and an invasive species (invasive alien species) is; consider whether a species could fall into more than one category.

74. A non-native species arriving in a new habitat/ecosystem must overcome three  barriers (filters) to be able to establish itself (colonize that habitat). Briefly describe each one and argue which you think is the greatest barrier to successful colonization.

75. Dispersal limitations are the greatest barrier to successful colonization. Describe what has caused an rapid increase in invasive/introduced species in the last 100 - 200 years.

76. Explain why most species fail to persist and successfully colonize a new habitat even when they are intentionally introduced.

77. List the four main ways species overcome the biotic barrier and are able to successfully establish themselves in a new environment. Use an example to describe one mechanism in detail.

78. Use an example to explain how invasive species may lead to species extinctions. Make sure to explicitly state factors that made species that went extinct vulnerable and factors that allowed the invasive species to have such a dramatic impact.

79. Briefly explain how invasive species may actually increase biodiversity. Argue whether or not you would consider this a positive impact on biodiversity.

80. The direct impacts of invasive species broadly fall into four categories. List all four categories and use a specific example to describe one mechanism in detail.

81. Lionfish have rapidly invaded the Gulf of Mexico and the Caribbean in the last 10 years. List key characteristics to explain what has made them such successful invaders and describe the direct and indirect impacts they have had on the ecosystems they invade.

82. List two ways invasive species can impact an entire ecosystem. Use a specific example to explain one of these in detail.

83. Describe how invasive species can have a large negative impact on local/national economies. List three examples.

84. List three reasons species are intentionally introduced with intended positive impacts.

85. List the four major categories of risk management for invasive species. Briefly describe the different steps/phases of a invasive species becoming established in an ecosystem and explain how the focus of management strategies will differ at each stage (relate this back to the four categories you listed).

86. List four characteristics of successful eradication programs and briefly explain how they contribute to a successful program.

87. The result of anthropogenic climate change is a global, simultaneous change of abiotic parameters. List six categories to organize components of climate change, list two examples for each category.

88. The impact of climate change is experienced across all levels of biodiversity from genes, species to ecosystems. List six categories to organize the types of responses, list two examples for each category.

89. Changing climate is altering conditions of native habitats, as a result species will either go extinct (die) or they must have the ability to adapt or migrate. Briefly describe the three major ways species can respond to persist despite an altered climatic niche.

90. Climate models use three types of predictors, spatial, demographic/life history, and recent trends. List three examples of parameters in each category and argue which type of predictors are more or less powerful predictors (argue includes stating which you think are better predictors and why).

91. List the four major categories of documented responses to climate change.

92. There is a range of documented cases of populations decaying (decreasing), some even resulting in local extirpations. Use two examples to explain two different mechanisms that can result in populations not being able to persist.

93. Briefly explain what a geographic range expansion/shift is (remember, this includes describing what a range expansion looks like, general patterns and explaining the mechanism behind it).

94. Describe what a geographic range expansion is and explain the difference between a cold edge expansion (leading edge expansion), and a warm edge contraction (trailing edge contraction). 

95. Use an example to explain how climate change may alter the fitness of a species through altered phenologies and resulting population asynchronies. Be sure to define both 'phenology' and 'population asynchrony' for your explanation.

96. Briefly describe what a regime shift is.

97. Use an example to explain how climate change may result in a regime shift (this includes defining what a regime shift is and the explaining the mechanism for the example you choose).

98. Climate change impacts biodiversity which in turn will impact ecosystem functioning and the provided ecosystem services. Use an example to explain how climate change negatively impacts human well-being and positively impacts human well-being through changes in ecosystem services.

99. List thee major strategies to manage & mitigate the effect of climate change on biodiversity. Use and example to explain one of the strategies in detail.

100. List two major ways we can use biodiversity to mitigate the effects of climate change. Use an example to explain one strategy in detail.

101. Compare and contrast the concepts of ecosystem resilience and ecosystem resistance.

102. Define what a regime shift is. Explain what a tipping point is in the context of a regime shift, list the four criteria to define a tipping point.

103. Use an example of a regime shift/tipping point to explain what a regime shift/tipping point is. This should include assessing the impact of specific drivers and the mechanisms of the tipping point as well as a clear definition of what a regime shift/tipping point is and how this example exemplifies those.

104. Tropic Coral Reefs are a prominent case study of a regime shift/tipping point. One of the main drivers is climate change. Explain how an increase in atmospheric CO2 has a direct and indirect effects on coral reefs. List other drivers of biodiversity loss in coral reef systems.



<br>

Download a hard copy of the recap questions [`r icon::fa("file-download")`](/files/BI328_ReviewQs_Biodiversity_Loss.pdf).
