---
title: "Conservation Biology (BI328)"
description: |
  Fall 2020 Course Site
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

```

# Course Schedule

*This is the current lecture schedule. Assigned readings will be posted at least one week in advance (see Content).*

::: l-body

| | WEEK  |DAY| LECTURE TOPIC                                                              | READING
|-|-------|---|----------------------------------------------------------------------------|------------
|1|	8/19  |	W	| [Introduction to Conservation Biology](https://bi328.netlify.app/lect_1)                | 2
|	|	      |   | **BIODIVERSITY: CONCEPTS, MEASURES, PATTERNS**                                          |
| |       | F	| [Rise & Fall of Biodiversity](https://bi328.netlify.app/lect_2)                         | 3, 4
|2|	8/24	| M |	[Defining Biodiversity](https://bi328.netlify.app/lect_2)                               | 3, 4
| |       |	W |	[Quantifying Biodiversity](https://bi328.netlify.app/lect_2)                            | 3, 4
| |       | F	| [Global Patterns](https://bi328.netlify.app/lect_2)                                     | 3, 4
|3| 8/31	| M	| [Functional Diversity](https://bi328.netlify.app/lect_2)                                | 3, 4
| |       | W	| [Drivers of Biodiversity](https://bi328.netlify.app/lect_3)                             | 
|	|	      |   | **THE VALUE OF BIODIVERSITY**	                                                          |
| |       | F	| [Value Systems](https://bi328.netlify.app/lect_3)                                       | 5, 6
| |       |   | *due 9/4 by midnight: Topics for case studies*                                          |
|4| 9/7	  | M	| [Value of Genetic, Species, Ecosystem Diversity](https://bi328.netlify.app/lect_3)      | 6, 7
| |       | W	| [Ecosystem Services](https://bi328.netlify.app/lect_3)                                  | 6, 7
| |       | F	| **MIDTERM**	                                                                            |
|5|	9/14	| M |	[Economics of Biodiversity](https://bi328.netlify.app/lect_4)                           | 7
|	|	      |   | **THE BIODIVERSITY CRISIS**                                                             |
| |       | W	| [Global, regional, local patterns of biodiversity loss](https://bi328.netlify.app/lect_4) | 8
| |       | F	| [Intrinsic Vulnerability & Habitat Loss](https://bi328.netlify.app/lect_4)              | 9
|6|	9/21	| M	| [Habitat Fragmentation & Metapopulations](https://bi328.netlify.app/lect_4)             | 9
| |       | W	| [Habitat Degradation](https://bi328.netlify.app/lect_4)                                 | 9
| |       | F	| [Pollution](https://bi328.netlify.app/lect_4)                                           | Diaz & Rosenberg 2008
|7|	9/28	| M	| [Overexploitation](https://bi328.netlify.app/lect_4)                                    | 10
| |       | W	| [Overfishing](https://bi328.netlify.app/lect_4)                                         | 10
| |       | F	| [Invasive Species](https://bi328.netlify.app/lect_4)                                    | 11
|8| 10/5  | M	| [Climate Change](https://bi328.netlify.app/lect_4)                                      | 12
| |       |   | *due 10/5 by midnight: outline/annotated bibliography*                                  |
| |       | W |	Special Topic: Wildfires                                                                |
| |       | F	| **MIDTERM**                                                                             |
|9|	10/12 |	M	| [Tipping Points, Resilience, Persistence](https://bi328.netlify.app/lect_5)             | Leadly 2010
|	|	      |   | **MAINTAINING, CONSERVING, AND RESTORING BIODIVERSITY**	                                |
| |       | W	| [Wildlife forensics & Wildlife trade](https://bi328.netlify.app/lect_5)                 |
| |       | F	| [Ex-situ conservation](https://bi328.netlify.app/lect_5)                                | 16
|10| 10/19| M |	[Species/population-level conservation/Estimating population sizes](https://bi328.netlify.app/lect_5)  | 13
| |       | W |	["SNOW" DAY]()                                                                                | 
| |       | F |	[Population models & predicting population persistence](https://bi328.netlify.app/lect_5)     | 13, Lacy 2019
|11| 10/26| M |	[The problem with small populations](https://bi328.netlify.app/lect_5)                        | 13
| |       | W |	[Conservation Genetics](https://bi328.netlify.app/lect_5)                                     | Hedrick & Fredrickson 2010, Schwartz et al 2007
| |       | F |	[Conservation Genetics](https://bi328.netlify.app/lect_5)                                     | Hedrick & Fredrickson 2010, Schwartz et al 2007
|12| 11/2 | M	| [Essential Habitats/Ecosystem-based management](https://bi328.netlify.app/)                   |
| |       | W	| [Ecosystem/Landscape-level Conservation](https://bi328.netlify.app/)                          |
| |       | F	| **MIDTERM**	                                                                                  |
|13| 11/9 |	M	| [Ecosystem/Landscape-level Conservation](https://bi328.netlify.app/)                          |
| |       | W	| [Ecosystem/Landscape-level Conservation](https://bi328.netlify.app/)                          |
| |       | F	| [Politics & Policy/domestic & international](https://bi328.netlify.app/)                      |
|14| 11/16| M	| [Sustainable Development](https://bi328.netlify.app/)                                         |
| |       | W |	[Ecopragmatism/Ecomodernism](https://bi328.netlify.app/)                                      |
| |       | F |	[The final word](https://bi328.netlify.app/)                                                  |
| |       |   | *due 11/23 by midnight: Term paper*                                                           |

:::

